### PR TITLE
Provide a toggle to suppress the soft warning about commercial use

### LINKED ISSUE #2963: No Documentation on Installing Commercial License
### Description

So, I purchased a commercial license from Xceed.  As a software developer, I wanted to support continued development as I use FluentAssertions extensively in my tests.  However, there is no documentation on how to install the license and disable the Console.WriteLine for the softWarning which I don't want to be part of my builds

Steps:
1) Go to Xceed. https://xceed.com/products/unit-testing/fluent-assertions/
2) Purchase license
3) Wait for receipt
4) Wait for license.  You may need to email sales@xceed.com as I'm not sure the licenses are automatically generated and emailed out.
5) Explore the documentation to find there is no mention of how to attach a license to a NuGet downloaded version of FluentAssertions, v8.

### Reproduction Steps

```csharp
// Arrange
string input = "MyString";

// Act
char result = input[0];

// Assert
result.Should().Be('M');
```

### Expected behavior

Expect:
* Documentation on how to disable the soft warning in my builds with a purchased license.
* More than just an email with a license key that doesn't do anything.  The commercial license should at least allow me to disable all of the warnings.

### Actual behavior

No changes.

### Regression?

I would call changing the licensing for v8 a regression.

### Known Workarounds

Stick with v7 or just ignore the warnings for v8.

### Configuration

_No response_

### Other information

_No response_

### Are you willing to help with a pull-request?

No

### PR DESCRIPTION
**Pull request by dennisdoomen**
Resolves #2963 by providing a toggle to suppress the license warning that happens during each test run.

### CODE REVIEW

File: Src/FluentAssertions/Licensing.cs [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+/// <summary>
+/// Provides access to the licensing state of Fluent Assertions
+/// </summary>
+public static class Licensing
+{
+    /// <summary>
+    /// Allows to disable or enable the warning that reminds consumers about the license requirements for commercial use.
+    /// </summary>
+    public static bool AcknowledgeSoftWarning { get; set; } = true;
```
Comment (jnyrup) [inline Src/FluentAssertions/Licensing.cs:11]: Shouldn't this be `false` by default?

Comment (jnyrup) [inline Src/FluentAssertions/Licensing.cs:11]: As an end user I'm not sure I would know what "soft warning" refers to.

I find "Acknowledge" too vague as it means "accept or admit the existence or truth of something".

What if one could call `License.Accept = true`?

**Review by jnyrup — CHANGES_REQUESTED** [review]

File: Src/FluentAssertions/Licensing.cs (hunk 1 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Licensing.cs:11]: But accept what?

Comment (jnyrup) [reply Src/FluentAssertions/Licensing.cs]: > But accept what?

The license.

Comment (dennisdoomen) [reply Src/FluentAssertions/Licensing.cs]: Alright. I can live with that.

**Review by jnyrup — APPROVED** [review]
