### PR TITLE
Optionally include internal members in equivalency assertions

### LINKED ISSUE #1205: BeEquivalentTo does not exclude internal members
`BeEquivalentTo` fails if an `internal` property has a different value.

The [documentation](https://fluentassertions.com/objectgraphs/), section "Including properties and/or fields" states:

> Barring other configuration, Fluent Assertions will include all **public** properties and fields

However, it also seems to take into account all `internal` properties and fields.

Who is wrong? The documentation or the implementation? What is `BeEquivalentTo` supposed to do?

In the following code sample, PrivateMembersShouldNotBeCompared succeeds but InternalMembersShouldNotBeCompared fails on the compare of property `InternalProperty`.
```C#
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject
{
    [TestClass]
    public class TestBeEquivalentTo
    {
        class TestSubject
        {
            private string PrivateProperty { get; }
            internal string InternalProperty { get; }
            public string PublicProperty { get; }

            public TestSubject(string privateString, string internalString, string publicString)
            {
                PrivateProperty = privateString;
                InternalProperty = internalString;
                PublicProperty = publicString;
            }
        }

        [TestMethod]
        public void PrivateMembersShouldNotBeCompared()
        {
            TestSubject first = new TestSubject("A", "A", "A");
            TestSubject second = new TestSubject("B", "A", "A");

            first.Should().BeEquivalentTo(second);
        }

        [TestMethod]
        public void InternalMembersShouldNotBeCompared()
        {
            TestSubject first = new TestSubject("A", "A", "A");
            TestSubject second = new TestSubject("B", "B", "A");

            first.Should().BeEquivalentTo(second);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by dennisdoomen**
`BeEquivalentTo` will no longer include `internal` properties and fields, unless `IncludingInternalProperties` or `IncludingInternalFields` is used

Fixes #1205, #744

* [x] Release notes

### CODE REVIEW

File: Src/FluentAssertions/Common/TypeExtensions.cs [hunk 1]
```diff
@@ -194,46 +197,62 @@ public static FieldInfo FindField(this Type type, string fieldName, Type preferr
...
-        public static IEnumerable<PropertyInfo> GetNonPrivateProperties(this Type typeToReflect,
-            IEnumerable<string> filter = null)
+        public static IEnumerable<PropertyInfo> GetNonPrivateProperties(this Type typeToReflect, MemberVisibility visibility)
         {
             IEnumerable<PropertyInfo> query =
-                from propertyInfo in GetPropertiesFromHierarchy(typeToReflect)
+                from propertyInfo in GetPropertiesFromHierarchy(typeToReflect, visibility)
                 where HasNonPrivateGetter(propertyInfo)
                 where !propertyInfo.IsIndexer()
-                where filter is null || filter.Contains(propertyInfo.Name)
```
Comment (jnyrup) [inline Src/FluentAssertions/Common/TypeExtensions.cs:212]: Was a `filter` never provided by any caller?
Is the functionality handled elsewhere since it was originally added?

File: Src/FluentAssertions/Common/TypeExtensions.cs [hunk 2]
```diff
@@ -194,46 +197,62 @@ public static FieldInfo FindField(this Type type, string fieldName, Type preferr
...
+        private static IEnumerable<PropertyInfo> GetPropertiesFromHierarchy(Type typeToReflect, MemberVisibility memberVisibility)
+        {
+            bool includeInternals = memberVisibility.HasFlag(MemberVisibility.Internal);
+
+            return GetMembersFromHierarchy(typeToReflect, type =>
+            {
+                return type
+                    .GetProperties(AllInstanceMembersFlag)
+                    .Where(property => property.GetMethod?.IsPrivate == false)
+                    .Where(property => includeInternals || property.GetMethod?.IsAssembly == false)
```
Comment (jnyrup) [inline Src/FluentAssertions/Common/TypeExtensions.cs:228]: How does this handle properties marked as `private protected` or `protected internal`?

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs [hunk 3]
```diff
@@ -58,7 +59,7 @@ public void Format(object value, FormattedObjectGraph formattedGraph, Formatting
         /// <remarks>The default is all non-private members.</remarks>
         protected virtual MemberInfo[] GetMembers(Type type)
         {
-            return type.GetNonPrivateMembers().ToArray();
+            return type.GetNonPrivateMembers(MemberVisibility.Public).ToArray();
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/DefaultValueFormatter.cs:62]: Does this mean that if two objects only differ in an internal member, the formatted objects only contains the identical public members?

File: Src/FluentAssertions/Common/TypeExtensions.cs (hunk 1 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Common/TypeExtensions.cs:212]: I tried to look back until 4.x and it wasn't even used then.

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs (hunk 3 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/DefaultValueFormatter.cs:62]: Yep. Good point. Maybe we should include the internal `members` as well? Making it configurable seems a bit much to me.

Comment (jnyrup) [reply Src/FluentAssertions/Formatting/DefaultValueFormatter.cs:62]: Without having any data to back me up, I think it might become too noisy for the default case if we include internal members.
E.g. for #889 one of the problems was that [HtmlNode](https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlNode.cs) has +20 internal backing fields.
Even with #899 when excluding already processed references, the formatted output has a lot of `avoiding circular references`.

If the failure message is clear enough about the missing/non-matching internal members, I would go with that for now and only print the public ones.

File: Src/FluentAssertions/Common/TypeExtensions.cs (hunk 2 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Common/TypeExtensions.cs]: AFAIK `private protected` is not relevant here, but `protect internal` was. I've added extra tests to cover this scenario.

File: Src/FluentAssertions/Common/TypeExtensions.cs [hunk 4]
```diff
@@ -284,12 +303,12 @@ private static Type[] GetInterfaces(Type type)
 
         private static PropertyInfo[] GetPublicProperties(Type type)
```
Comment (jnyrup) [inline Src/FluentAssertions/Common/TypeExtensions.cs:304]: `GetPublicProperties` and `GetPublicFields` are now unused.

File: Src/FluentAssertions/Common/TypeExtensions.cs (hunk 2 above)
Comment (jnyrup) [reply Src/FluentAssertions/Common/TypeExtensions.cs]: I'm wondering a bit about what that means to protected members.

We ignore `protected` members
unless it's `protected internal`
unless it `private protected`?

**Comment by dennisdoomen** [comment]
> I'm wondering a bit about what that means to protected members.
> We ignore protected members
> unless it's protected internal
> unless it private protected?

Why do you care about `protected` members? They are not `public`, nor `internal`.

**Comment by jnyrup** [comment]
I do not care about `protected`, I just mixed them up.
It made sense to me after seeing it visualized as a Venn Diagram like https://stackoverflow.com/a/22958035/1087627

**Review by jnyrup — APPROVED** [review]
