### PR TITLE
Prevent `InvalidOperationException` when formatting lambda expression

### LINKED ISSUE #2175: InvalidOperationException while asserting Expressions with custom EqualityComparer
### Description

The class `FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter` throws an exception when an assertion fails between two lambda expressions that initialize their members from a parameter. 

### Reproduction Steps

```csharp
using FluentAssertions;
using System.Linq.Expressions;
using Xunit;

namespace FluentAssertionTests;

public class FluentAssertionExceptionTest
{
    [Fact]
    public void BeEquivalentTo_WithEqualityComparer_ShouldNotThrowInvalidOperationException()
    {
        // Arrange
        Expression a = (string arg) => new TestItem { Value = arg };
        Expression b = (string arg) => new TestItem { Value = arg };

        // Act
        a.Should().BeEquivalentTo(b, options => options.Using(new ExpressionEqualityComparer()));
    }

    private record TestItem
    {
        public string? Value { get; set; }
    }

    private class ExpressionEqualityComparer : IEqualityComparer<Expression>
    {
        public bool Equals(Expression? x, Expression? y) => false;

        public int GetHashCode(Expression obj) => default;
    }
}
```

### Expected behavior

```
Xunit.Sdk.XunitException
Expected a to be equal to TestItem { Value =  arg } according to "FluentAssertionTests.FluentAssertionExceptionTest+ExpressionEqualityComparer", but TestItem { Value =  arg  } was not.
```

### Actual behavior

```
System.InvalidOperationException
When called from 'VisitMemberInit', rewriting a node of type 'System.Linq.Expressions.NewExpression' must return a non-null value of the same type. Alternatively, override 'VisitMemberInit' and change it to not visit children of this type.
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](T node, String callerName)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ConstantSubExpressionReductionVisitor.Visit(Expression node)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ReduceConstantSubExpressions(Expression expression)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.Format(Object value, FormattedObjectGraph formattedGraph, FormattingContext context, FormatChild formatChild)
   at FluentAssertions.Formatting.Formatter.Format(Object value, FormattedObjectGraph output, FormattingContext context, FormatChild formatChild)
   at FluentAssertions.Formatting.Formatter.ToString(Object value, FormattingOptions options)
   at FluentAssertions.Execution.MessageBuilder.<FormatArgumentPlaceholders>b__6_0(Object a)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at FluentAssertions.Execution.MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
   at FluentAssertions.Execution.MessageBuilder.Build(String message, Object[] messageArgs, String reason, ContextDataItems contextData, String identifier, String fallbackIdentifier)
   at FluentAssertions.Execution.AssertionScope.<>c__DisplayClass38_0.<FailWith>b__0()
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Execution.GivenSelector`1.FailWith(String message, Object[] args)
   at FluentAssertions.Equivalency.Steps.EqualityComparerEquivalencyStep`1.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
   at FluentAssertions.Equivalency.Steps.RunAllUserStepsEquivalencyStep.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
   at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.RecursivelyAssertEquality(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
   at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
   at FluentAssertionTests.FluentAssertionExceptionTest.BeEquivalentTo_WithEqualityComparer_ShouldNotThrowInvalidOperationException()
```

### Regression?

_No response_

### Known Workarounds

Create a custom ValueFormatter to ignore the default PredicateLambdaExpressionValueFormatter:
```csharp
public class FluentAssertionExceptionTest
{
    public FluentAssertionExceptionTest()
    {
        Formatter.AddFormatter(new LambdaExpressionFormatter());
    }

    private class LambdaExpressionFormatter : DefaultValueFormatter
    {
        public override bool CanHandle(object value) => value is LambdaExpression;
    }

    ...
}
```

### Configuration

.NET 7.0.100
FluentAssertions 6.10.0

### Other information

The exception seems to be because the NewExpression under an InitMemberExpression [doesn't contain any ParameterExpression and is considered a constant](https://github.com/fluentassertions/fluentassertions/blob/d4c4eb5b1df000f44fe14facc07d54c32457e57f/Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs#LL94C45-L94C71).

### PR DESCRIPTION
**Pull request by jnyrup**
## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

Prevent `InvalidOperationException` when formatting lambda expression calling a constructor

This fixes #2175

### CODE REVIEW

File: Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs [hunk 1]
```diff
@@ -91,7 +100,9 @@ public override Expression Visit(Expression node)
                 return node;
             }
 
-            if (!HasLiftedOperator(node) && ExpressionIsConstant(node))
+            if (node is not (MemberInitExpression or NewExpression)
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:103]: 🤔 That took me a couple of times before I was convinced I was reading this correctly.

File: Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs [hunk 2]
```diff
@@ -11,6 +11,38 @@ public class PredicateLambdaExpressionValueFormatterSpecs
 {
     private readonly PredicateLambdaExpressionValueFormatter formatter = new();
 
+    [Fact]
+    public void Constructor_expression_with_argument_is_not_reduced()
```
Comment (dennisdoomen) [inline Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs:15]: 🤔 "Reduced"? I didn't get it.

Comment (jnyrup) [reply Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs:15]: Yeah... I also struggled with naming this one.

`ConstantSubExpressionReductionVisitor` tries to "reduce" expressions, but threw an exception when trying to reduce this one.

Brain storming better names:
`Constructor_expression_with_argument_can_be_formatted`
`Formatting_a_constructor_expression_with_argument_does_not_throw`

File: Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs (hunk 1 above)
Comment (jnyrup) [reply Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:103]: The logical expression `!(p or q)` ([De Morgan's Law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws)), the readability of the code or that it programmatically works?

Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:103]: The readability

File: Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs (hunk 2 above)
Comment (dennisdoomen) [reply Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs:15]: > Constructor_expression_with_argument_can_be_formatted

👍

**Review by dennisdoomen — APPROVED** [review]
