### PR TITLE
Limit formatting to a maximum number of lines

### LINKED ISSUE #1014: Assertion crunches for too long on assertion failure on complex graph objects
I am running XUnit tests using **AngleSharp** for HTML inspection and **FluentAssertions** for assertions. It turns out that when an assertion fails on a `IElement` object, the test run ends up spinning for such a long time, hugging up a CPU core.

### Complete minimal example reproducing the issue
The following code depends on [AngleSharp](https://github.com/AngleSharp/AngleSharp).

```csharp
// Arrange
var someMarkup = @"<p id=""paragraph"">This is an element</p>";

var parser = new AngleSharp.Html.Parser.HtmlParser();
var document = parser.ParseDocument(someMarkup);

// Act
IElement element = document.QuerySelector("#paragraph");

// Assert
element.Should().BeNull(); // at this point element is not null, and the assertion should fail
```

### Expected behavior:
My test should fail, since element is null. Using the _non-null_ primitive, I don't require to have a complete description of my _non-null_ object.

### Actual behavior:
It takes so much time formatting the string for the `IElement` object that the tests ends up timeout. If I am running under Visual Studio, Visual Studio will just become non responsive for more than five minutes (I didn't try to let it run further)

### Versions
**FluentAssertions** `5.6.0`
**.NET Core** `2.2.0`
**AngleSharp** `0.11.0`

### Additional Information
When you look at the structure of the `IElement` object, you can see that it was structure with a lot of HTML navigation concepts, such as (`Child`, `NextSibling`, `Parent`). The graph has no leaf. 

The current implementation of cyclic reference detection works well, but the possible combination/permutation of properties within this class is making the `Formatter` needlessly trying to get all the properties through different navigational properties.

Wouldn't there be a reasonable limit to how much formatting should dig properties ? At some point, having +100 properties display seems (to me) plainly too much. In this case I've printed more than 12000 and estimated that I am not even at 8% of what I could have print...

### PR DESCRIPTION
**Pull request by dennisdoomen**
* Formatter.ToString will take an options object that allow you to specify the max depth and the max number of lines to produce
Both will have defaults
* AssertionScope will have properties to override this in case you need it
* Also considering to have the defaults come from AssertionOptions
* Limit formatting to a maximum number of lines

Fixes #1014

**Can be reviewed commit by commit**

### CODE REVIEW

File: Src/FluentAssertions/Formatting/FormattingOptions.cs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+        /// Determines the maximum number of lines the library should use to render an object graph.
+        /// </summary>
+        public int MaxLines { get; set; } = 100;
+
+        public FormattingOptions Clone()
+        {
+            return new()
+            {
+                UseLineBreaks = UseLineBreaks,
+                MaxDepth = MaxDepth
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormattingOptions.cs:28]: Should an updated `MaxLines` be included in the cloning?

Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/FormattingOptions.cs:28]: Good catch. I'm not done yet though ;-)

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs [hunk 2]
```diff
@@ -57,48 +61,43 @@ protected virtual MemberInfo[] GetMembers(Type type)
...
-
         private static bool HasDefaultToStringImplementation(object value)
         {
             string str = value.ToString();
 
             return str is null || str == value.GetType().ToString();
         }
 
-        private string GetTypeAndMemberValues(object obj, FormattingContext context, FormatChild formatChild)
+        private void WriteTypeAndMemberValues(object obj, FormattedObjectGraph output, FormatChild formatChild)
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/DefaultValueFormatter.cs:71]: 🔧 Consistency if we use `FormattedObjectGraph output` or `FormattedObjectGraph formattedGraph` (multiple places)

File: Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs [hunk 3]
```diff
@@ -297,5 +299,40 @@ public bool CanHandle(IEquivalencyValidationContext context, IEquivalencyAsserti
...
+            {
+                Given(() =>
+                {
+                    oldSettings = AssertionOptions.FormattingOptions.Clone();
+                });
+
+                When(() =>
+                {
+                    AssertionOptions.FormattingOptions.UseLineBreaks = true;
+                    AssertionOptions.FormattingOptions.MaxDepth = 123;
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs:318]: Include `MaxLines` in the test

File: Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs [hunk 4]
```diff
@@ -219,19 +229,76 @@ public void
...
             // Act
-            string result = Formatter.ToString(head);
+            string result = Formatter.ToString(head, new FormattingOptions
+            {
+                MaxDepth = maxDepth
+            });
 
             // Assert
-            result.Should().ContainEquivalentOf("maximum recursion depth");
+            result.Should().ContainEquivalentOf($"maximum recursion depth of {maxDepth}");
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs:250]: nit: are you being too DRY here when including `maxDepth` from the Arrange phase in the Assert phase?

File: Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs [hunk 5]
```diff
@@ -219,19 +229,76 @@ public void
...
+            {
+                var newHead = new Node();
+                node.Children.Add(newHead);
+                node = newHead;
+            }
+
+            // Act
+            string result = Formatter.ToString(head, new FormattingOptions
+            {
+                    // Each iteration adds two levels of depth to the graph
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs:271]:
```suggestion
                // Each iteration adds two levels of depth to the graph
```

File: Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs [hunk 6]
```diff
@@ -1,5 +1,7 @@
 ﻿using System;
 using System.Collections.Generic;
+using System.ComponentModel.DataAnnotations;
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs:3]: delete

File: Src/FluentAssertions/Formatting/FormatChild.cs [hunk 7]
```diff
@@ -0,0 +1,13 @@
+﻿namespace FluentAssertions.Formatting
+{
+    /// <summary>
+    /// Represents a method that can be used to format child values from inside a <see cref="IValueFormatter"/>.
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormatChild.cs:4]:
```suggestion
    /// Represents a method that can be used to format child values from inside an <see cref="IValueFormatter"/>.
```

File: Src/FluentAssertions/Formatting/FormatChild.cs [hunk 8]
```diff
@@ -0,0 +1,13 @@
...
+    /// </summary>
+    /// <param name="childPath">
+    /// Represents the path from the current location to the child value.
+    /// </param>
+    /// <param name="value">
+    /// The child value to run through the configured <see cref="IValueFormatter"/>s.
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormatChild.cs:10]: 🔧
```suggestion
    /// The child value to format with the configured <see cref="IValueFormatter"/>s.
```

File: Src/FluentAssertions/Formatting/FormattedObjectGraph.cs [hunk 9]
```diff
@@ -0,0 +1,131 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using FluentAssertions.Execution;
+
+namespace FluentAssertions.Formatting
+{
+    /// <summary>
+    /// This class is used by the <see cref="Formatter"/> class to collect all the output of the (nested calls of a) <see cref="IValueFormatter"/> into
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormattedObjectGraph.cs:10]:
```suggestion
    /// This class is used by the <see cref="Formatter"/> class to collect all the output of the (nested calls of an) <see cref="IValueFormatter"/> into
```

File: Src/FluentAssertions/Formatting/FormattedObjectGraph.cs [hunk 10]
```diff
@@ -0,0 +1,131 @@
...
+    /// a the final representation.
+    /// </summary>
+    /// <remarks>
+    /// The <see cref="FormattedObjectGraph"/> will ensure that the number of lines will be limited
+    /// to the maximum lines provided through its constructor. It will throw
+    /// a <see cref="MaxLinesExceededException"/> when the maximum has been reached.
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormattedObjectGraph.cs:16]: 🔧 (as we often do not reach the limit)
```suggestion
    /// a <see cref="MaxLinesExceededException"/> if the maximum has been reached.
```

File: Src/FluentAssertions/Formatting/FormattedObjectGraph.cs [hunk 11]
```diff
@@ -0,0 +1,131 @@
...
+
+namespace FluentAssertions.Formatting
+{
+    /// <summary>
+    /// This class is used by the <see cref="Formatter"/> class to collect all the output of the (nested calls of a) <see cref="IValueFormatter"/> into
+    /// a the final representation.
+    /// </summary>
+    /// <remarks>
+    /// The <see cref="FormattedObjectGraph"/> will ensure that the number of lines will be limited
+    /// to the maximum lines provided through its constructor. It will throw
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormattedObjectGraph.cs:15]:
```suggestion
    /// to the maximum number of lines provided through its constructor. It will throw
```

File: Src/FluentAssertions/Formatting/FormattedObjectGraph.cs [hunk 12]
```diff
@@ -0,0 +1,131 @@
...
+        /// </summary>
+        public void AddLine(string line)
+        {
+            FlushCurrentLine();
+
+            AppendSafely(Whitespace + line);
+        }
+
+        /// <summary>
+        /// Starts or continues the current line with additional fragments of text.
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormattedObjectGraph.cs:64]: ❓ I'm not sure what the additional fragments in the plural "fragments" refer to.

File: Src/FluentAssertions/Formatting/XAttributeValueFormatter.cs [hunk 13]
```diff
@@ -1,3 +1,4 @@
+using System.Collections.Generic;
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/XAttributeValueFormatter.cs:1]: delete (in multiple of the Formatters)

File: Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt [hunk 14]
```diff
@@ -1,12 +1,5 @@
-<<<<<<< HEAD:Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
```
Comment (jnyrup) [inline Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt]: If you want a cleaner git history, you could avoid introducing and reverting this git conflict stuff from 6d7c1179f711cab78601543fcbb2ca3393826cfd and cfb709574e53e0f50310d36fbd6b8774c57b233c

File: Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs [hunk 15]
```diff
@@ -8,13 +10,21 @@
...
 {
     [Collection("FormatterSpecs")]
     public class FormatterSpecs
     {
+        private readonly ITestOutputHelper outputHelper;
+
+        public FormatterSpecs(ITestOutputHelper outputHelper)
+        {
+            this.outputHelper = outputHelper;
+        }
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs:26]: ❓ What does these do?

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs [hunk 16]
```diff
@@ -28,22 +25,29 @@ public virtual bool CanHandle(object value)
...
+        public void Format(object value, FormattedObjectGraph formattedGraph, FormattingContext context, FormatChild formatChild)
         {
             if (value.GetType() == typeof(object))
             {
-                return $"System.Object (HashCode={value.GetHashCode()})";
+                formattedGraph.AddFragment($"System.Object (HashCode={value.GetHashCode()})");
+                return;
             }
 
-            string prefix = context.Options.UseLineBreaks ? Environment.NewLine : string.Empty;
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/DefaultValueFormatter.cs]: I can't really tell if it makes a difference and if so, if it's better or worse.
`UseLineBreaks` is ignored in `WriteTypeAndMemberValues`.

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs [hunk 17]
```diff
@@ -57,48 +61,43 @@ protected virtual MemberInfo[] GetMembers(Type type)
...
-        private string GetTypeAndMemberValues(object obj, FormattingContext context, FormatChild formatChild)
+        private void WriteTypeAndMemberValues(object obj, FormattedObjectGraph output, FormatChild formatChild)
         {
-            var builder = new StringBuilder();
-
-            if (context.Depth == RootLevel)
-            {
-                builder.AppendLine();
-                builder.AppendLine();
-            }
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/DefaultValueFormatter.cs:83]: Is this handled elsewhere (maybe in `FormattedObjectGraph`) or is this a change for the better?

**Review by jnyrup — COMMENTED** [review]
As requested, here's your additional "shitload of comments"

File: Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs (hunk 4 above)
Comment (dennisdoomen) [reply Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs:250]: I decided to do it like that because I also include it in the calculations.

File: Src/FluentAssertions/Formatting/FormattedObjectGraph.cs (hunk 12 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/FormattedObjectGraph.cs:64]: I rephrased it. Hopefully it clarifies it a bit better now.

File: Src/FluentAssertions/Formatting/XAttributeValueFormatter.cs (hunk 13 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/XAttributeValueFormatter.cs:1]: Because Rider collapses the `using` statements by default, it started to care less about them. But cleaned them up for you ;-)

File: Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs (hunk 15 above)
Comment (dennisdoomen) [reply Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs:26]: Removed them. That's the only way in xUnit to dump some output in the unit test results.

File: Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt (hunk 14 above)
Comment (dennisdoomen) [reply Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt]: It's going to be quite some work to clean that up. I would have to rebuild the commits one by one. Or I could just squash everything together. It's your call.

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs (hunk 16 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/DefaultValueFormatter.cs]: If the formatter needs to render the object with its properties, it will always do that as a multi-line representation.

File: Src/FluentAssertions/Formatting/DefaultValueFormatter.cs (hunk 17 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/DefaultValueFormatter.cs:83]: It was no longer needed.

File: Src/FluentAssertions/Formatting/FormatChild.cs [hunk 18]
```diff
@@ -0,0 +1,13 @@
...
+    /// <summary>
+    /// Represents a method that can be used to format child values from inside an <see cref="IValueFormatter"/>.
+    /// </summary>
+    /// <param name="childPath">
+    /// Represents the path from the current location to the child value.
+    /// </param>
+    /// <param name="value">
+    /// The child value to format with the configured <see cref="IValueFormatter"/>s.
+    /// </param>
+    public delegate void FormatChild(string childPath, object value, FormattedObjectGraph output);
```
Comment (jnyrup) [inline Src/FluentAssertions/Formatting/FormatChild.cs:12]: `output` -> `formattedGraph`.
Consider adding `<param>` for the new parameter.

File: Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs [hunk 19]
```diff
@@ -297,5 +299,42 @@ public bool CanHandle(IEquivalencyValidationContext context, IEquivalencyAsserti
...
+            {
+                AssertionScope.Current.FormattingOptions.UseLineBreaks.Should().BeTrue();
+                AssertionScope.Current.FormattingOptions.MaxDepth.Should().Be(123);
+                AssertionScope.Current.FormattingOptions.MaxLines.Should().Be(33);
+            }
+
+            protected override void Dispose(bool disposing)
+            {
+                AssertionOptions.FormattingOptions.MaxDepth = oldSettings.MaxDepth;
+                AssertionOptions.FormattingOptions.UseLineBreaks = oldSettings.UseLineBreaks;
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs:334]: Should `MaxLines` be restored?

File: Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt (hunk 14 above)
Comment (jnyrup) [reply Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt]: I don't care enough for it that should you spend time on it. 
Your time/effort is more appreciated elsewhere. 
Let's keep the commit history as it is nicely separated into logical changes.

**Review by jnyrup — APPROVED** [review]
Awesome!
I can't wait to see some failing unit tests

**Comment by jnyrup** [comment]
Just noticed that the docs also needs an update. 

https://fluentassertions.com/extensibility/#rendering-objects-with-beauty

**Comment by dennisdoomen** [comment]
> Just noticed that the docs also needs an update.

Damnit. I already did the work to update the extensibility guide and add a section to the tips for migrating to v6. I must have force pushed something away.

File: docs/_pages/extensibility.md [hunk 20]
```diff
@@ -95,18 +95,19 @@ So in this case, our nicely created `ContainFile` extension method will display
...
+void Format(object value, FormattedObjectGraph formattedGraph, FormattingContext context, FormatChild formatChild);
 ```
 
 Next to the actual value that needs rendering, this method accepts a couple of parameters worth mentioning.
 
+* `formattedGraph` is the object that collects the textual representation of the entire graph. It supports adding fragments of text, full lines and deals with automatic identation using its `WithIndentation` method. It also protects the performance of the rendering by throwing a `MaxLinesExceededException` when the textual representation has exceeded the configured maximum.  
 * `context.UseLineBreaks` denotes that the value should be prefixed by a newline. It is used by some assertion code to force displaying the various elements of the failure message on a separate line.
-* `context.Depth` is used when rendering a complex object that would involve multiple, potentially recursive, nested calls through `formatChild`. It allows the formatter to display its representation using an indented view.
+* `formatChild` is used when rendering a complex object that would involve multiple, potentially recursive, nested calls through
```
Comment (jnyrup) [inline docs/_pages/extensibility.md:110]: Unfinished sentence?
