### PR TITLE
Harden DataSet types against a continuing AssertionScope

### LINKED ISSUE #1530: Exceptions from DataSet Assertions
### Description
Ran all unit tests in the `develop` branch and noted that we threw some unexpected exceptions.

`When_Columns_do_not_match_and_property_is_not_excluded_it_should_fail` throws a `NullReferenceException`.
```
FluentAssertions.Data.DataEquivalencyAssertionOptions`1.ShouldExcludeColumn(DataColumn column) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataEquivalencyAssertionOptions.cs:line 300
FluentAssertions.Equivalency.DataRowEquivalencyStep.CompareFieldValues(IEquivalencyValidationContext context, IEquivalencyValidator parent, DataRow subject, DataRow expectation, DataEquivalencyAssertionOptions`1 dataSetConfig, DataEquivalencyAssertionOptions`1 dataTableConfig, DataEquivalencyAssertionOptions`1 dataRowConfig) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataRowEquivalencyStep.cs:line 128
FluentAssertions.Equivalency.DataRowEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataRowEquivalencyStep.cs:line 65
FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 128
FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 52
FluentAssertions.Equivalency.DataRowCollectionEquivalencyStep.MatchRowsByIndexAndCompare(IEquivalencyValidationContext context, IEquivalencyValidator parent, DataRowCollection subject, DataRowCollection expectation) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataRowCollectionEquivalencyStep.cs:line 74
FluentAssertions.Equivalency.DataRowCollectionEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataRowCollectionEquivalencyStep.cs:line 47
FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 128
FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 52
FluentAssertions.Equivalency.DataTableEquivalencyStep.CompareCollections(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config, Dictionary`2 selectedMembers) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataTableEquivalencyStep.cs:line 158
FluentAssertions.Equivalency.DataTableEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataTableEquivalencyStep.cs:line 62
FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 128
FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 52
FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 36
FluentAssertions.Data.DataTableAssertions`1.BeEquivalentTo(DataTable expectation, Func`2 config, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataTableAssertions.cs:line 258
FluentAssertions.Data.DataTableAssertions`1.BeEquivalentTo(DataTable expectation, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataTableAssertions.cs:line 177
FluentAssertions.Specs.DataEquivalencySpecs.DataTableEquivalencySpecs.<>c__DisplayClass22_0.<When_Columns_do_not_match_and_property_is_not_excluded_it_should_fail>b__0() in C:\dev\fluentassertions\Tests\FluentAssertions.Specs\Equivalency\DataEquivalencySpecs.DataTable.cs:line 429
FluentAssertions.Specialized.ActionAssertions.InvokeSubject() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\ActionAssertions.cs:line 25
FluentAssertions.Specialized.DelegateAssertions`2.InvokeSubjectWithInterception() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 221
```

`When_Rows_do_not_match_and_property_is_not_excluded_it_should_fail` throws an `IndexOutOfRangeException`.
```
FluentAssertions.Equivalency.DataRowCollectionEquivalencyStep.MatchRowsByIndexAndCompare(IEquivalencyValidationContext context, IEquivalencyValidator parent, DataRowCollection subject, DataRowCollection expectation) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataRowCollectionEquivalencyStep.cs:line 67
FluentAssertions.Equivalency.DataRowCollectionEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataRowCollectionEquivalencyStep.cs:line 47
FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 128
FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 52
FluentAssertions.Equivalency.DataTableEquivalencyStep.CompareCollections(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config, Dictionary`2 selectedMembers) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataTableEquivalencyStep.cs:line 158
FluentAssertions.Equivalency.DataTableEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataTableEquivalencyStep.cs:line 62
FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 128
FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 52
FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 36
FluentAssertions.Data.DataTableAssertions`1.BeEquivalentTo(DataTable expectation, Func`2 config, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataTableAssertions.cs:line 258
FluentAssertions.Data.DataTableAssertions`1.BeEquivalentTo(DataTable expectation, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataTableAssertions.cs:line 177
FluentAssertions.Specs.DataEquivalencySpecs.DataTableEquivalencySpecs.<>c__DisplayClass32_0.<When_Rows_do_not_match_and_property_is_not_excluded_it_should_fail>b__0() in C:\dev\fluentassertions\Tests\FluentAssertions.Specs\Equivalency\DataEquivalencySpecs.DataTable.cs:line 662
FluentAssertions.Specialized.ActionAssertions.InvokeSubject() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\ActionAssertions.cs:line 25
FluentAssertions.Specialized.DelegateAssertions`2.InvokeSubjectWithInterception() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 221
```
@logiclrd do you by any change have time to look at these?

### PR DESCRIPTION
**Pull request by jnyrup**
In 44efddb454397f15c50068ca5b5245b4542317db `ShouldExcludeColumn` threw an NRE when `subjectColumn` was null.
This is now null guarded to avoid checking whether a non-existing column should be excluded.
A few lines below `subjectColumn` and `expectationColumn` are compared and potential null values are taken into account.

In 03fffcd `DataRowCollectionEquivalencyStep.OnHandle` did check `subject.Count == expectation.Count` before invoking `MatchRowsByIndexAndCompare` which threw an `IndexOutOfRangeException`, but it didn't take into account being on a continuing `AssertionScope`.

I also added some more `AssertionScope` guards to the `DataSet` related classes in 03fffcd.

This fixes #1530

### CODE REVIEW

File: Src/FluentAssertions/Equivalency/DataSetEquivalencyStep.cs [hunk 1]
```diff
@@ -161,52 +161,63 @@ private static void CompareTables(IEquivalencyValidationContext context, IEquiva
         {
             if (selectedMembers.ContainsKey(nameof(expectation.Tables)))
             {
-                AssertionScope.Current
+                bool success = AssertionScope.Current
                     .ForCondition(subject.Tables.Count == expectation.Tables.Count)
                     .FailWith("Expected {context:DataSet} to contain {0}, but found {1} table(s)", expectation.Tables.Count, subject.Tables.Count);
 
-                if (dataConfig is not null)
+                if (success)
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Equivalency/DataSetEquivalencyStep.cs:168]: 🔧 Maybe jumping out of the method when `success` is `false` may make this method better readable.

**Review by dennisdoomen — APPROVED** [review]

File: Src/FluentAssertions/Equivalency/DataSetEquivalencyStep.cs (hunk 1 above)
Comment (jnyrup) [reply Src/FluentAssertions/Equivalency/DataSetEquivalencyStep.cs:168]: As in an early return?
I would be happy to do that instead, I only avoided it for your sake.

Comment (dennisdoomen) [reply Src/FluentAssertions/Equivalency/DataSetEquivalencyStep.cs:168]: In this case, it would make total sense.
