### PR TITLE
Limits the depth of rendering an object to a max of 5

### LINKED ISSUE #889: OutOfMemory exception when using assertions on HtmlNodeCollection
### Description

When trying to check an HtmlNodeCollection (HtmlAgilityPack) for NullOrEmpty we are getting an OutOfMemory exception. Upon quick investigation there seems to be an infinite loop in Formater.FormatChild method.

### Complete minimal example reproducing the issue

```
var col = new HtmlNodeCollection(new HtmlNode(HtmlNodeType.Element, new HtmlDocument(), 0));
col.Add(new HtmlNode(HtmlNodeType.Element, new HtmlDocument(), 0));
col.Should().BeNullOrEmpty();
```

### Expected behavior:

Assertion should fail with error message

### Actual behavior:

OutOfMemoryException

### Versions

FluentAssertions 5.4.1.0
.NET framework 4.6.1

### PR DESCRIPTION
**Pull request by dennisdoomen**
I see no value in rendering a graph 15 levels deep. This should help prevent OOM exceptions while rendering an object graph. 

Fixes #889

### CODE REVIEW

File: Src/FluentAssertions/Formatting/Formatter.cs [hunk 1]
```diff
@@ -115,7 +113,7 @@ private static string FormatChild(string path, object childValue, bool useLineBr
                 {
                     return $"{{Cyclic reference to type {childValue.GetType()} detected}}";
                 }
-                else if (graph.Depth > MaxDepth)
+                else if (graph.Depth > 5)
```
Comment (Meir017) [inline Src/FluentAssertions/Formatting/Formatter.cs]: Maybe make this configurable instead of constant?

Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/Formatter.cs]: Personally I don't see why anybody would ever see an object graph in their unit test output window that goes beyond 5 levels deep.

Comment (Meir017) [reply Src/FluentAssertions/Formatting/Formatter.cs]: Maybe for comparing json or xml objects?

**Comment by jnyrup** [comment]
A lot of the problem seems to be that `HtmlNode` declare it's backing fields as `internal` which we also print along the public property. 

Couldn't we detect that e.g. `_ownerDocument` and `OwnerDocument` references the same object in memory and only print out `OwnerDocument`?

File: Src/FluentAssertions/Formatting/Formatter.cs (hunk 1 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Formatting/Formatter.cs]: For that we have specialized APIs that don't require cyclic reference detection (which is the real cause of the problem mentioned here)

**Comment by dennisdoomen** [comment]
I believe we already skip it because of the recursive detection. The real issue is that we somehow include private and internal fields and properties. I think that's something we should change (in a separate PR).

**Comment by dennisdoomen** [comment]
> When I run the test, the failure message both contains the internal field _ownerdocument and the public property OwnerDocument.
> OwnerDocument is just returning _ownerdocument.
> https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlNode.cs
> It's the same case for _parentnode and ParentNode
> 
> Could it be that we also select internal members that are not marked as VisibleTo the running test?
> It seems we also pick internal members of Encoding

We should fix both of them.
