### PR TITLE
Filter the list of events returned by RaisePropertyChangeFor

### LINKED ISSUE #393: ShouldRaisePropertyChangedFor followed by Count behaves unexpectedly (solution here)
I wanted to check the number of times `RaisePropertyChanged` had been raised for a particular property.

I expected to type:

```c#
myVm.ShouldRaisePropertyChangedFor(vm => vm.myProperty).Count().ShouldBeEquivalentTo(2);
```

This failed - the count returned was for ALL RaisePropertyChange events, not the specific one I am testing.

I have written a quick extension method:

```c#
public static int SpecificRaisePropertyChangedCount(this IEnumerable<RecordedEvent> value, string propertyName)
{
    return value.Select(r => r.Parameters)
        .SelectMany(s => s)
        .Count(p => p is PropertyChangedEventArgs && (p as PropertyChangedEventArgs).PropertyName == propertyName);
}
```

so you can now do:

```c#
myVm.ShouldRaisePropertyChangedFor(vm => vm.myProperty)
    .SpecificRaisePropertyChangedCount(nameof(myVm.myProperty))
    .ShouldBeEquivalentTo(2);
```

Sorry I haven't submitted this as a pull request - I'm up to my neck in it and no time to clone the repo etc, but feel free to add it or whatever (or tell me that I could have done it with the existing code easily ^_^ )

### PR DESCRIPTION
**Pull request by arocheleau**
The call to `RaisePropertyChangeFor` on `EventAssertions<T>` now returns a filtered list of events related to the property given as parameter.  The `NotRaisePropertyChangeFor` function has been revised as well to match the behavior of `RaisePropertyChangeFor` especially when the parameter provided is `null`.

This fixes #393.

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

File: Src/FluentAssertions/Events/EventAssertions.cs [hunk 1]
```diff
@@ -144,13 +144,29 @@ public void NotRaise(string eventName, [StringSyntax("CompositeFormat")] string
     {
         IEventRecording recording = Monitor.GetRecordingFor(PropertyChangedEventName);
 
-        string propertyName = propertyExpression.GetPropertyInfo().Name;
+        string propertyName = propertyExpression?.GetPropertyInfo().Name;
 
-        if (recording.Any(@event => GetAffectedPropertyName(@event) == propertyName))
+        if (string.IsNullOrEmpty(propertyName))
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Events/EventAssertions.cs:149]: 🤔 I don't think `propertyName` can ever be empty here. It can only be a valid name or `null`

File: Src/FluentAssertions/Events/EventAssertions.cs [hunk 2]
```diff
@@ -144,13 +144,29 @@ public void NotRaise(string eventName, [StringSyntax("CompositeFormat")] string
...
+        }
+        else
         {
             Execute.Assertion
                 .BecauseOf(because, becauseArgs)
-                .FailWith("Did not expect object {0} to raise the {1} event for property {2}{reason}, but it did.",
+                .ForCondition(!recording.Any(@event =>
+                {
+                    var affectedPropertyName = GetAffectedPropertyName(@event);
+
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Events/EventAssertions.cs:165]: ♻️ We can make this more readable by wrapping all of this and the `GetAffectedPropertyName` logic into `OccuredEvent`.

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs [hunk 3]
```diff
@@ -540,6 +540,53 @@ public void
...
+        [Fact]
+        public void
+            The_number_of_property_changed_recorded_for_a_specific_property_matches_the_number_of_time_it_was_raised_including_agnostic_property()
+        {
+            // Arrange
+            var subject = new EventRaisingClass();
+            using var monitor = subject.Monitor();
+            subject.RaiseEventWithSenderAndPropertyName(nameof(EventRaisingClass.SomeProperty));
+            subject.RaiseEventWithSenderAndPropertyName(nameof(EventRaisingClass.SomeOtherProperty));
+            subject.RaiseEventWithSenderAndPropertyName(null);
```
Comment (dennisdoomen) [inline Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:568]: 🤔`INotifyPropertyChanged` does not allow a `null` property. But if remove the line from this test that passes `null`, the test fails. I didn't expect that.

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs [hunk 4]
```diff
@@ -540,6 +540,53 @@ public void
             act.Should().Throw<XunitException>()
                 .WithMessage("Expected*property*SomeProperty*but*OtherProperty1*OtherProperty2*");
         }
+
+        [Fact]
+        public void
+            The_number_of_property_changed_recorded_for_a_specific_property_matches_the_number_of_time_it_was_raised_specifically()
```
Comment (dennisdoomen) [inline Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:546]: ⛏️ The number of time_s_

**Comment by dennisdoomen** [comment]
@arocheleau just to be clear, if you have addressed the comments, please mark them as resolved and re-request a review. Then I'll know when to look at the rework.

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs (hunk 3 above)
Comment (arocheleau) [reply Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:568]: The remark section of the [documentation page](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=net-8.0#system-componentmodel-inotifypropertychanged-propertychanged) for `INotifyPropertyChanged.PropertyChanged` mentions that the property name of the `PropertyChangedEventArgs` could be `null` or `string.Empty` to target all properties.

Comment (dennisdoomen) [reply Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:568]: Yeah, you're right. I'm at loss what I was thinking at that time. However, shouldn't the assertion then not expect 4 events?

Comment (ITaluone) [reply Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:568]: It makes sense for me as it is, because he's checking for `x.SomeProperty` which isn't matching for `SomeOtherProperty`, but for everything else in this case.

Comment (arocheleau) [reply Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:568]: The purpose of this test was to make sure all events related to a single property is being returned as expected.  3 out of 4 events are raised for this purpose ("SomeProperty", `null` and `string.Empty`).  The last event is targeting "SomeOtherProperty" and should not be returned or count in the final result.  The reason it was added to the test was to validate that the function is actually returning a filtered list of events and not the full list.  To achieve this, I added an event, an intruder, that is not supposed to be returned.

**Review by dennisdoomen — APPROVED** [review]
Great work

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs [hunk 5]
```diff
@@ -540,6 +540,53 @@ public void
...
+        {
+            // Arrange
+            var subject = new EventRaisingClass();
+            using var monitor = subject.Monitor();
+            subject.RaiseEventWithSenderAndPropertyName(nameof(EventRaisingClass.SomeProperty));
+            subject.RaiseEventWithSenderAndPropertyName(nameof(EventRaisingClass.SomeProperty));
+            subject.RaiseEventWithSenderAndPropertyName(nameof(EventRaisingClass.SomeOtherProperty));
+
+            // Act
+            monitor.Should().RaisePropertyChangeFor(x => x.SomeProperty).Count().Should().Be(2);
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:556]:
```suggestion
            monitor.Should().RaisePropertyChangeFor(x => x.SomeProperty).Should().HaveCount(2);
```

**Review by jnyrup — APPROVED** [review]

File: Src/FluentAssertions/Events/EventAssertions.cs [hunk 6]
```diff
@@ -15,8 +15,6 @@ namespace FluentAssertions.Events;
 /// </summary>
 public class EventAssertions<T> : ReferenceTypeAssertions<T, EventAssertions<T>>
 {
-    private const string PropertyChangedEventName = "PropertyChanged";
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/EventAssertions.cs:18]: > r just to replace the string literal "PropertyChanged" with nameof(INotifyPropertyChanged.PropertyChanged)?

Just this part.

**Comment by dennisdoomen** [comment]
@arocheleau Let me know if you want to do something with the suggestions from @jnyrup so we know when to merge this PR.

**Comment by arocheleau** [comment]
@dennisdoomen I have applied the suggestions from @jnyrup

**Review by jnyrup — APPROVED** [review]
