### PR TITLE
Make `ThatAreUnderNamespace` respect null namespaces and prefixes

### LINKED ISSUE #1185: TypeSelector.ThatAreUnderNamespace(null) behaves inconsistently and throws exceptions
### Description

Issue originally reported here and in further comments: https://github.com/fluentassertions/fluentassertions/issues/1175#issuecomment-551813648

### Complete minimal example reproducing the issue

For classes:

``` cs
class ClassInGlobalNamespace { }

namespace DummyNamespace {
    class ClassInDummyNamespace { }
}
```

And for type selectors:
``` cs
var typeInGlobalNamespace = typeof(ClassInGlobalNamespace);
var typesInGlobalNamespace = new TypeSelector(typeInGlobalNamespace);

var typeInDummyNamespace = typeof(ClassInDummyNamespace);
var typesInDummyNamespace = new TypeSelector(typeInDummyNamespace);
```

### Expected behavior:

All types are _under_ the global namespace. No types are _not under_ the global namespace.

``` cs
typesInGlobalNamespace.ThatAreUnderNamespace(typeInGlobalNamespace.Namespace).AsEnumerable().Should().HaveCount(1);
typesInGlobalNamespace.ThatAreUnderNamespace(null).AsEnumerable().Should().HaveCount(1);

typesInGlobalNamespace.ThatAreNotUnderNamespace(typeInGlobalNamespace.Namespace).AsEnumerable().Should().HaveCount(0);
typesInGlobalNamespace.ThatAreNotUnderNamespace(null).AsEnumerable().Should().HaveCount(0);

typesInDummyNamespace.ThatAreUnderNamespace(null).AsEnumerable().Should().HaveCount(1);
typesInDummyNamespace.ThatAreNotUnderNamespace(null).AsEnumerable().Should().HaveCount(0);
```

### Actual behavior:

Types in the global namespace are both _under_ and _not under_ it. The filtering methods throw exceptions when run for types not in the global namespace.

``` cs
typesInGlobalNamespace.ThatAreUnderNamespace(typeInGlobalNamespace.Namespace).AsEnumerable().Should().HaveCount(0);
typesInGlobalNamespace.ThatAreUnderNamespace(null).AsEnumerable().Should().HaveCount(0);

typesInGlobalNamespace.ThatAreNotUnderNamespace(typeInGlobalNamespace.Namespace).AsEnumerable().Should().HaveCount(0);
typesInGlobalNamespace.ThatAreNotUnderNamespace(null).AsEnumerable().Should().HaveCount(0);

Action thatAreUnderNamespace = () => typesInDummyNamespace.ThatAreUnderNamespace(null);
Action thatAreNotUnderNamespace = () => typesInDummyNamespace.ThatAreNotUnderNamespace(null);
thatAreUnderNamespace.Should().Throw<ArgumentNullException>();
thatAreNotUnderNamespace.Should().Throw<ArgumentNullException>();
```

### Versions

* Which version of Fluent Assertions are you using?
Newest master branch.

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET Framework 4.5, .NET Framework 4.7, .NET Core 2.0, and .NET Core 3.0.

### Additional Information

Suggested fix is to change the `ThatAreUnderNamespace` and `ThatAreNotUnderNamespace` methods from:

``` cs
public TypeSelector ThatAreUnderNamespace(string @namespace)
{
    types = types.Where(t.Namespace?.StartsWith(@namespace) == true).ToList();
    return this;
}

public TypeSelector ThatAreNotUnderNamespace(string @namespace)
{
    types = types.Where(t => t.Namespace?.StartsWith(@namespace) != true).ToList();
    return this;
}
```

to:

``` cs
public TypeSelector ThatAreUnderNamespace(string @namespace)
{
    types = types.Where(t => @namespace == null || t.Namespace?.StartsWith(@namespace) == true).ToList();
    return this;
}

public TypeSelector ThatAreNotUnderNamespace(string @namespace)
{
    types = types.Where(t => @namespace != null && t.Namespace?.StartsWith(@namespace) != true).ToList();
    return this;
}
```

However, this would be a breaking change. There are not currently tests that run `ThatAreUnderNamespace(null)` or `ThatAreNotUnderNamespace(null)`.

### PR DESCRIPTION
**Pull request by jnyrup**
The namespace of a type not inside any namespace is `null`.
As all types are *under* the global namespace, `ThatAreUnderNamespace` should be able to gracefully handle `null` namespaces.

This also fixes that `ThatAreUnderNamespace` would incorrectly match the
namespace of a type against a partial prefix.

This fixes #1185 and #1196

### CODE REVIEW

File: Src/FluentAssertions/Common/TypeExtensions.cs [hunk 1]
```diff
@@ -588,5 +588,13 @@ internal static bool IsDerivedFromOpenGeneric(this Type type, Type definition)
 
             return false;
         }
+
+        internal static bool IsUnderNamespace(this Type type, string @namespace)
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Common/TypeExtensions.cs]: I think we should break this complicated statement into smaller chunks.
