### PR TITLE
BeEmpty() materializes IEnumerable<T> only once, even on failure

### LINKED ISSUE #2490: IEnumerable gets evaluated multiple times when using BeEmpty()
### Description

There seems to be an issue with `BeEmpty()` when used with `IEnumerable`. The `IEnumerable` gets evaluated multiple times, leading to unexpected behavior.

### Reproduction Steps

```csharp
private bool a = false;

public IEnumerable<string> Get()
{
    if (a)
    {
        yield break;
    }

    a = true;
    yield return "123";
}

[TestMethod]
public void Execute()
{
    var result = Get();

    result.Should().BeEmpty();
}
```

### Expected behavior

I expect the test to fail, with the message: "Expected result to be empty, but found {"123"}."

### Actual behavior

Test fails, but with the message: "Expected result to be empty, but found {empty}."

### Regression?

_No response_

### Known Workarounds

Converting the `IEnumerable` to a list before asserting solves the issue:
```csharp
[TestMethod]
public void Execute()
{
    var result = Get().ToList();

    result.Should().BeEmpty();
}
```

### Configuration

FluentAssertions version: 6.12.0
.NET version: 7.0

### Other information

The issue seems to arise from how Fluent Assertions handles the evaluation of `IEnumerable`. Ensuring the collection is evaluated only once before the emptiness check might resolve this issue.

### Are you willing to help with a pull-request?

No

### PR DESCRIPTION
**Pull request by louis-z**
- Make BeEmpty() materialize only the first item, as no further processing is needed for validation
- The error message now mentions "but found at least one item" and outputs the said item

Fixes #2490

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

File: Src/FluentAssertions/Collections/GenericCollectionAssertions.cs [hunk 1]
```diff
@@ -285,15 +285,16 @@ public AndConstraint<TAssertions> AllBeOfType(Type expectedType, string because
...
             .WithExpectation("Expected {context:collection} to be empty{reason}, ")
-            .Given(() => Subject)
+            .Given(() => singleItemArray)
             .ForCondition(subject => subject is not null)
             .FailWith("but found <null>.")
             .Then
-            .ForCondition(subject => !subject.Any())
-            .FailWith("but found {0}.", Subject)
+            .ForCondition(subject => subject.Length == 0)
+            .FailWith("but found at least 1 item {0}.", singleItemArray)
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:297]: 🤔 I've been trained that numbers up to 10 should be spelled out as "one", "two", etc. Not sure if that applies here.

**Review by dennisdoomen — APPROVED** [review]

**Review by jnyrup — APPROVED** [review]

**Comment by jnyrup** [comment]
A note: This partly reverts #227, but I'm fine with the change here.
A similar change should be applied to `BeNullOrEmpty` to keep them aligned.

**Comment by louis-z** [comment]
> [...] A similar change should be applied to `BeNullOrEmpty` to keep them aligned.

Will do.

**Comment by jnyrup** [comment]
Aren't we missing a test for `BeNullOrEmpty` identical to the added `When_asserting_non_empty_collection_is_empty_it_should_enumerate_only_once` test to verify the change?

**Comment by dennisdoomen** [comment]
Fair point.

**Comment by bogataj** [comment]
@dennisdoomen did this change also unintentionally affect WithMessage on ExceptionAssertions? Release notes only mentions BeEmpty() and BeNullOrEmpty(), but I have tests failing now after upgrading 6.12.0 -> 6.12.1 where the iterator seem to stop after the first item at that method also. 

Specifically my use case is a generic convention test that finds and prints all missing subscription registrations on a service bus, stopping the iteration on the first item while evaluating WithMessage would be a somewhat unfortunate feature, while I appreciate the efforts for performance gains 👍

**Comment by jnyrup** [comment]
@bogataj Please share a code example of what no longer works for you.

In the meantime I would suggest that if your test requires complete enumeration, that you enforce it on your side instead of relying on that we (or any other library) does that.

**Comment by bogataj** [comment]
@jnyrup My apologize, I usually start with a sample but for some reason this time I didnt. While deconstructing my tests to prepare a sample, I found that we were actually chaining the results between tests, basing the original message off an BeEmpty(), so this is my bad and the update to the library does exactly as is says, thank you.
