### PR TITLE
Pass down the reason to inner `AssertionScope`

### LINKED ISSUE #2293: Equivalency assertion for dictionary does not include because message
### Description

When comparing the values of dictionaries for equivalency, the `because` message is not included in the failure message.

### Reproduction Steps

```csharp
var subject = new Dictionary<string, object>
{
    ["a"] = new List<int>()
};

var expected = new Dictionary<string, object>
{
    ["a"] = new List<int> { 42 }
};

subject.Should().BeEquivalentTo(expected, "FOO");
```

### Expected behavior

Exception message should include `FOO`

### Actual behavior

```
FluentAssertions.Execution.AssertionFailedException: 'Expected subject[a] to be a collection with 1 item(s), but found an empty collection.

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.
'
```

### Regression?

no

### Known Workarounds

_No response_

### Configuration

Fluent Assertions 6.12
.NET 8.0

### Other information

_No response_

### Could you help with a pull-request?

Yes

### PR DESCRIPTION
**Pull request by IT-VBFK**
This fixes #2293 

## IMPORTANT 

* [x] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by IT-VBFK** [comment]
Qodana thinks we aren't in pr_mode? 🤔

**Comment by jnyrup** [comment]
> Qodana thinks we aren't in pr_mode? 🤔

We fiddled with the [Qodana pipeline](https://github.com/fluentassertions/fluentassertions/blob/develop/.github/workflows/code_quality.yml) today. Apparently we didn't nail it 😞 
I have pushed a change to `develop` 🤞 
Try rebasing on `develop`.

**Comment by jnyrup** [comment]
Try rebasing one more time.

image

**Comment by IT-VBFK** [comment]
Can I close #2319 then?

**Comment by jnyrup** [comment]
> Can I close #2319 then?

Yes.

File: Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyValidator.cs [hunk 1]
```diff
@@ -34,6 +34,8 @@ public EnumerableEquivalencyValidator(IEquivalencyValidator parent, IEquivalency
 
     public void Execute<T>(object[] subject, T[] expectation)
     {
+        AssertionScope.Current.BecauseOf(context.Reason);
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyValidator.cs:37]: 🤔 I think you need to solve this problem at a different place. When a new nested `AssertionScope` is created, such as [here](https://github.com/fluentassertions/fluentassertions/blob/a832de3ed8987188d13cf4ae33bf4413e6137f9a/Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs#L157), it should automatically pick up the _reason_ from the parent. This should be fixed [here](https://github.com/fluentassertions/fluentassertions/blob/de9fa4d63ffad9444657558ae690ccbcc789dfc2/Src/FluentAssertions/Execution/AssertionScope.cs#L106).

**Review by dennisdoomen — CHANGES_REQUESTED** [review]

File: Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs [hunk 2]
```diff
@@ -1170,4 +1170,22 @@ public void When_a_custom_rule_is_applied_on_a_dictionary_it_should_apply_it_on_
...
+        };
+
+        var expected = new Dictionary<string, object>
+        {
+            ["a"] = new List<int> { 42 }
+        };
+
+        Action act = () => subject.Should().BeEquivalentTo(expected, "FOO");
+
+        act.Should().Throw<XunitException>().WithMessage("*FOO*");
```
Comment (jnyrup) [inline Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs:1189]: To ensure we pass both `because` and `becauseArgs` all the way.
```suggestion
        Action act = () => subject.Should().BeEquivalentTo(expected, "FOO {1}", "BAR");

        act.Should().Throw<XunitException>().WithMessage("*FOO BAR*");
```

File: Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyValidator.cs (hunk 1 above)
Comment (IT-VBFK) [reply Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyValidator.cs:37]: Thank you at pointing me at the correct location ♥️

File: Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs (hunk 2 above)
Comment (IT-VBFK) [reply Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs]: I think this should be `{0}`, isn't it? 😉

Comment (jnyrup) [reply Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs]: 🤐

**Comment by jnyrup** [comment]
Something's up with our Qodana pipeline.
It seems to be scanning the wrong commit.

@dennisdoomen 
Should this line https://github.com/fluentassertions/fluentassertions/blob/73ff4e012398a64d30244ff8993199706c6a7cb7/.github/workflows/code_quality.yml#L18 also use `pull_request_target` instead of `pull_request`?

**Comment by dennisdoomen** [comment]
> also use `pull_request_target` instead of `pull_request`?

No, there's no such thing. Instead, I think we should use 

`ref: "${{ github.event.pull_request.merge_commit_sha }}"`

See also https://github.com/actions/checkout/issues/518#issuecomment-890401887

**Comment by IT-VBFK** [comment]
> Something's up with our Qodana pipeline.
> It seems to be scanning the wrong commit.

Rebased on current `develop`... let's see whether this helps..
