### PR TITLE
Better support for default interface and explicitly implemented properties

### LINKED ISSUE #2754: BeEquivalentTo doesn't always choose normal properties over explicitly implemented properties
### Description

I use my own implementation of Exception which implements a interface with a Message-Property. This property is of another type.

### Reproduction Steps

```csharp
[Fact]
public void Test()
{
    var instance = new MyClass()
    {
        MyError = 42,
    };
    var other = new MyClass()
    {
        MyError = 42,
    };

    instance.Should().BeEquivalentTo(other);
}

public class MyClass : Exception, IMyInterface
{
    public int MyError { get; set; }
    int IMyInterface.Message => MyError;
}

public interface IMyInterface
{
    int Message { get; }
}
```

### Expected behavior

The test passes.

### Actual behavior

The test failes with the message:

```
Message: 
Expected property instance.MyNamespace.IMyInterface.Message to be System.String, but found System.Int32.

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.


  Stack Trace: 
XUnit2TestFramework.Throw(String message)
TestFrameworkProvider.Throw(String message)
CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
AssertionScope.Dispose()
EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs)
MyTestClass.Test() line 426
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### Regression?

In 6.12.0 it worked by with 6.12.1 it is failing.

### Known Workarounds

_No response_

### Configuration

net8.0
FluentAssertions 6.12.1

### Other information

_No response_

### Are you willing to help with a pull-request?

No

### PR DESCRIPTION
**Pull request by dennisdoomen**
Reimplemented the Reflection process using a content-only open-source library needed to find all types of properties and fields including default interface properties.

Fixes #2754 and #2759

### CODE REVIEW

**Comment by ITaluone** [comment]
🤔 Missing release notes and/or documentation?

**Comment by ITaluone** [comment]
image

Do we really want this?

**Comment by dennisdoomen** [comment]
> image
> 
> Do we really want this?

Nope. You're right. I need to fix that.

File: Build/Build.cs [hunk 1]
```diff
@@ -259,6 +259,7 @@ void ReportTestOutcome(params string[] globFilters)
                     ReportTypes.lcov,
                     ReportTypes.HtmlInline_AzurePipelines_Dark)
                 .AddFileFilters("-*.g.cs")
+                .AddFileFilters("-**/.nuget/**")
```
Comment (ITaluone) [inline Build/Build.cs:262]: Maybe I am wrong, but I think this should be: `-*.nuget*.cs`, since it supports wildcard but not glob filters.

Comment (dennisdoomen) [reply Build/Build.cs:262]: I think you're right.

Comment (ITaluone) [reply Build/Build.cs]: Hmm.. apparently I wasn't.. I don't how to handle this then, because this behind the scenes is converted to a regex and and a `Regex.IsMatch()` is performed:

https://github.com/danielpalme/ReportGenerator/blob/15c6fc1004070c26689d4c30110b81d05d256544/src/ReportGenerator.Core/Parser/Filtering/DefaultFilter.cs#L73-L99

Comment (dennisdoomen) [reply Build/Build.cs]: I think it's fixed now.

**Review by ITaluone — APPROVED** [review]

File: Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+{
+    private static readonly ConcurrentDictionary<MemberVisibility, MemberKind> Cache = new();
+
+    public static MemberKind ToMemberKind(this MemberVisibility visibility)
+    {
+        return Cache.GetOrAdd(visibility, v =>
+        {
+            MemberKind result = MemberKind.None;
+
+            foreach (MemberVisibility flag in Enum.GetValues(typeof(MemberVisibility)))
```
Comment (jnyrup) [inline Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs:17]: We could polyfill `Enum.GetValues<T>` for older frameworks like we've done for other APIs in e.g. `SystemExtensions` and `StringBuilderExtensions` that PolySharp doesn't already provide.

| Method     | Job                  | Runtime              | Mean      | Error     | StdDev    | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|----------- |--------------------- |--------------------- |----------:|----------:|----------:|------:|--------:|-------:|----------:|------------:|
| NonGeneric | .NET 8.0             | .NET 8.0             | 101.05 ns |  0.896 ns |  0.794 ns |  1.00 |    0.01 | 0.0076 |      48 B |        1.00 |
| Generic    | .NET 8.0             | .NET 8.0             |  32.72 ns |  0.272 ns |  0.241 ns |  0.32 |    0.00 | 0.0076 |      48 B |        1.00 |
|            |                      |                      |           |           |           |       |         |        |           |             |
| NonGeneric | .NET Framework 4.7.2 | .NET Framework 4.7.2 | 744.11 ns | 14.475 ns | 15.488 ns |  1.00 |    0.03 | 0.0267 |     169 B |        1.00 |
| Generic    | .NET Framework 4.7.2 | .NET Framework 4.7.2 | 738.11 ns |  3.947 ns |  3.692 ns |  0.99 |    0.02 | 0.0267 |     169 B |        1.00 |

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using System;

BenchmarkRunner.Run<GetValuesBenchmark>();

[MemoryDiagnoser]
[SimpleJob(RuntimeMoniker.Net472)]
[SimpleJob(RuntimeMoniker.Net80)]
public class GetValuesBenchmark
{
    [Benchmark(Baseline = true)]
    public MemberVisibility[] NonGeneric() => (MemberVisibility[])Enum.GetValues(typeof(MemberVisibility));

    [Benchmark]
#if NET6_0_OR_GREATER
    public MemberVisibility[] Generic() => Enum.GetValues<MemberVisibility>();
#else
    public MemberVisibility[] Generic() => (MemberVisibility[])Enum.GetValues(typeof(MemberVisibility));
#endif
}

[Flags]
public enum MemberVisibility
{
    None = 0,
    Internal = 1,
    Public = 2,
    ExplicitlyImplemented = 4,
    DefaultInterfaceProperties = 8
}
```

File: Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+
+namespace FluentAssertions.Equivalency;
+
+internal static class MemberVisibilityExtensions
+{
+    private static readonly ConcurrentDictionary<MemberVisibility, MemberKind> Cache = new();
+
+    public static MemberKind ToMemberKind(this MemberVisibility visibility)
+    {
+        return Cache.GetOrAdd(visibility, v =>
```
Comment (jnyrup) [inline Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs:13]: To have the compiler help enforce that we don't capture anything
```suggestion
        return Cache.GetOrAdd(visibility, static v =>
```

Comment (dennisdoomen) [reply Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs:13]: Cool. Didn't know about this one.

File: Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs (hunk 2 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Equivalency/MemberVisibilityExtensions.cs]: I just used an #ifdef for now.

**Review by jnyrup — APPROVED** [review]
