### PR TITLE
Event constraining extensions WithArgs and WithSender will return matching events

### LINKED ISSUE #337: IEventRecorder .WithArgs<T> returns unfiltered IEventRecorder - feature / room for improvement?
I just noticed an somewhat unexpected behaviour testing events for one of my classes:

Given the following test

```c#
[Fact]
public void AddRangeRaisesPropertyChangedEventForItemIndexer()
{
	// given
	using (var observableDictionary = new ObservableDictionary<int, string>())
	{
		observableDictionary.ThresholdAmountWhenItemChangesAreNotifiedAsReset = 0;
		observableDictionary.MonitorEvents();

		var items = new List<KeyValuePair<int, string>>()
		{
			new KeyValuePair<int, string>(1, "One"),
			new KeyValuePair<int, string>(2, "Two"),
			new KeyValuePair<int, string>(3, "Three"),
		};

		// when
		observableDictionary.AddRange(items);

		// then
		observableDictionary
			.ShouldRaise(nameof(observableDictionary.PropertyChanged))
			.WithSender(observableDictionary)
			.WithArgs<PropertyChangedEventArgs>(args => args.PropertyName == "Item[]")
			.Should().HaveCount(1);
	}
}
```

I get a failing test because Count (the very last line) was expected to be 1, but it is 2.

Now the thing is - exactly one event is being raised for `Item[]`, the second one is for a different property (.Count).

Looking at the source of [PropertyChangedSourceExtensions.cs](https://github.com/dennisdoomen/fluentassertions/blob/e240c8c8d02160fd69e22d7590901df429f86bd3/Src/Core/PropertyChangedSourceExtensions.cs#L164) it becomes apparent that currently the IEventRecorder instance is returned back _as-is_ and not a filtered-down version using the supplied predicate.

I was expecting that every .With*() method here checks for the condition and if it passes, it returns the filtered eventRecorder back so one can actually fluently chain up checks.

I.e.:
- `.ShouldRaise(nameof(observableDictionary.PropertyChanged))` checks for any events for the given name, fails if none are raised or if they are, returns a filtered EventRecorder back only containing those events
- `.WithSender(observableDictionary)` then checks whether those ("PropertyChanged") events have the given sender, fails if not OR if they do, return a further filtered EventRecorder back - only containing "PropertyChanged" events back with the given sender
- `.WithArgs<PropertyChangedEventArgs>(args => args.PropertyName == "Item[]")` - same here: takes the (fluently filtered) stream and checks whether the PropertyName is the expected one, fails if not but if they are, again, returns a further filtered eventRecorder back.. and so on and so on. 

Currently it works 'unfiltered' / fluently for apparently all the .With\* event related methods there, but is this something worth considering/changing or am I just doing/expecting it wrong? :)

Cheers,
-J

### PR DESCRIPTION
**Pull request by dennisdoomen**
* Event constraining extensions `WithArgs` and `WithSender` will return only the events that match the constraints
* Several event raising assertion APIs will return an `IEventRecording` instead of `IEventRecorder` 
* The classes `EventMonitor` and `RecordedEvent` are now treated as `internal` code 
* Renamed method `GetEventRecorder` of interface `IMonitor` to `GetRecordingFor` and will return `IEventRecording`

Fixes #337

### CODE REVIEW

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 1]
```diff
@@ -13,84 +15,171 @@ namespace FluentAssertions
...
+                {
+                    eventsMatchingPredicate.Add(@event);
+                }
             }
 
-            if (eventRecorder.All(recordedEvent => !recordedEvent.Parameters.OfType<T>().Any(parameter => compiledPredicate(parameter))))
+
+            if (!hasArgumentOfRightType)
+            {
+                throw new ArgumentException("No argument of event " + eventRecording.EventName + " is of type <" + typeof(T) + ">.");
```
Comment (jnyrup) [inline Src/FluentAssertions/EventRaisingExtensions.cs:86]: Should this be an assertion fail instead?

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 2]
```diff
@@ -13,84 +15,171 @@ namespace FluentAssertions
...
+                    string.Join(" | ", predicates.Where(p => p != null).Select(p => p.Body.ToString())));
             }
 
-            return eventRecorder;
+            return new FilteredEventRecording(eventRecording, eventsMatchingPredicate);
+        }
+    }
+
+
+    internal class FilteredEventRecording : IEventRecording
```
Comment (jnyrup) [inline Src/FluentAssertions/EventRaisingExtensions.cs:149]: separate file

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 3]
```diff
@@ -13,84 +15,171 @@ namespace FluentAssertions
...
+        {
+            EventObject = eventRecorder.EventObject;
+            EventName = eventRecorder.EventName;
+            EventHandlerType = eventRecorder.EventHandlerType;
+
+            occurredEvents = events.ToArray();
+        }
+
+        public object EventObject { get; }
+        public string EventName { get; }
```
Comment (jnyrup) [inline Src/FluentAssertions/EventRaisingExtensions.cs:163]: newline between properties

File: Src/FluentAssertions/Events/EventMonitor.cs [hunk 4]
```diff
@@ -30,6 +30,7 @@ public EventMonitor(object eventSource, Func<DateTime> utcNow)
 
         public T Subject => (T)subject.Target;
 
+
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventMonitor.cs:33]: extra newline

File: Src/FluentAssertions/Events/EventRecorder.cs [hunk 5]
```diff
@@ -121,6 +116,20 @@ public void Reset()
                 }
             }
         }
+        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventRecorder.cs:119]: missing newline above

File: Src/FluentAssertions/Events/EventRecorder.cs [hunk 6]
```diff
@@ -121,6 +116,20 @@ public void Reset()
...
+
+        public IEnumerator<OccurredEvent> GetEnumerator()
+        {
+            foreach (RecordedEvent @event in raisedEvents.ToArray())
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventRecorder.cs:123]: Should there be a lock around `raisedEvent.ToArray()`?

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs [hunk 7]
```diff
@@ -554,11 +624,7 @@ public void When_monitoring_an_object_it_should_monitor_all_the_events_it_expose
                 // Assert
                 metadata.Should().BeEquivalentTo(new[]
                 {
-                    new
-                    {
-                        EventName = nameof(ClassThatRaisesEventsItself.InterfaceEvent),
-                        HandlerType = typeof(EventHandler)
-                    },
+                    new {EventName = nameof(ClassThatRaisesEventsItself.InterfaceEvent), HandlerType = typeof(EventHandler)},
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:627]: Why was this condensed to a single line?

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs [hunk 8]
```diff
@@ -630,7 +691,8 @@ private object CreateProxyObject()
                 AssemblyBuilderAccess.Run);
             ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule(assemblyName.Name, false);
             string typeName = baseType.Name + "_GeneratedForTest";
-            TypeBuilder typeBuilder = moduleBuilder.DefineType(typeName, TypeAttributes.Public, baseType, new[] { interfaceType });
+            TypeBuilder typeBuilder =
+ moduleBuilder.DefineType(typeName, TypeAttributes.Public, baseType, new[] { interfaceType });
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:695]: Random hit on enter?

File: docs/_pages/releases.md [hunk 9]
```diff
@@ -22,6 +22,7 @@ sidebar:
 **Fixes**
 * Reported actual value when it contained `{{{{` or `}}}}` - [#1234](https://github.com/fluentassertions/fluentassertions/pull/1234).
 * Changed dictionary assertion `NotContainKeys` to honour the key comparer if applicable - [#1233](https://github.com/fluentassertions/fluentassertions/pull/1233).
+* Event raising assertions like `WithSender`, `WithArgs` will only return the events that match the constraints - [#1321](https://github.com/fluentassertions/fluentassertions/pull/1321)
```
Comment (jnyrup) [inline docs/_pages/releases.md:25]:
```suggestion
* Event raising assertions like `WithSender` and `WithArgs` will only return the events that match the constraints - [#1321](https://github.com/fluentassertions/fluentassertions/pull/1321)
```

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 10]
```diff
@@ -13,84 +15,171 @@ namespace FluentAssertions
...
+                    hasArgumentOfRightType = true;
+                }
+
+                int parametersToCheck = Math.Min(typedParameters.Length, predicates.Length);
 
                 bool isMatch = true;
-                for (int i = 0; i < parametersToCheck && isMatch; i++)
+                for (int index = 0; index < parametersToCheck && isMatch; index++)
+                {
+                    isMatch = compiledPredicates[index]?.Invoke(typedParameters[index]) ?? true;
```
Comment (jnyrup) [inline Src/FluentAssertions/EventRaisingExtensions.cs:122]: Just to double check, is it intended that when `compiledPredicates[index]` returns null `isMatch` should be true?

File: Src/FluentAssertions/Execution/AssertionScope.cs [hunk 11]
```diff
@@ -224,11 +224,30 @@ private Continuation FailWith(Func<string> failReasonFunc)
             }
         }
 
+        /// <summary>
+        /// Registers a failure message that does not contain any formatting placeholders.
+        /// </summary>
+        public Continuation FailWith(string message)
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/Execution/AssertionScope.cs:230]: If I don't add it, I end up with an ambiguous call between the one that takes a `params` array of `object` and the one that takes a `params` array of `Func<object>`

File: Src/FluentAssertions/Events/EventAssertions.cs [hunk 12]
```diff
@@ -132,17 +130,17 @@ public void NotRaise(string eventName, string because = "", params object[] beca
         /// Zero or more values to use for filling in any <see cref="string.Format(string,object[])"/> compatible placeholders.
         /// </param>
         /// <remarks>
-        /// You must call <see cref="AssertionExtensions.Monitor"/> on the same object prior to this call so that Fluent Assertions can
+        /// You mu    st call <see cref="AssertionExtensions.Monitor"/> on the same object prior to this call so that Fluent Assertions can
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/EventAssertions.cs:133]: Removed those extra remarks. They were already irrelevant when we moved to the tread-safe implementation of `Monitor`

File: Src/FluentAssertions/EventRaisingExtensions.cs (hunk 1 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/EventRaisingExtensions.cs:86]: I'm not sure. It looks like a programming error if you provide the wrong generic type to `WithArgs`

File: Src/FluentAssertions/Events/EventRecorder.cs (hunk 6 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/EventRecorder.cs:123]: No, because it's a `BlockingCollection`. Wondering if I should change the name of field to make that clearer.

File: Src/FluentAssertions/EventRaisingExtensions.cs (hunk 10 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/EventRaisingExtensions.cs:122]: Yes, because you can pass `null` for a predicate to ignore that value.

File: Src/FluentAssertions/Events/EventHandlerFactory.cs [hunk 13]
```diff
@@ -27,7 +27,7 @@ public static Delegate GenerateHandler(Type eventSignature, IEventRecorder recor
                 AppendParameterListThisReference(parameters),
                 module);
 
-            MethodInfo methodToCall = typeof(IEventRecorder).GetMethod("RecordEvent",
+            MethodInfo methodToCall = typeof(EventRecorder).GetMethod("RecordEvent",
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventHandlerFactory.cs:30]: Does this silences the warning about `RecordEvent` being unused?
I assume that's why you added `[UsedImplicitly]`.

```suggestion
            MethodInfo methodToCall = typeof(EventRecorder).GetMethod(nameof(EventRecorder.RecordEvent),
```

File: Src/FluentAssertions/Events/EventHandlerFactory.cs [hunk 14]
```diff
@@ -13,7 +13,7 @@ internal static class EventHandlerFactory
         /// Generates an eventhandler for an event of type eventSignature that calls RegisterEvent on recorder
         /// when invoked.
         /// </summary>
-        public static Delegate GenerateHandler(Type eventSignature, IEventRecorder recorder)
+        public static Delegate GenerateHandler(Type eventSignature, IEventRecording recorder)
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventHandlerFactory.cs:16]: It seems this can only ever by an `EventRecorder`.
I haven't experimented, but wouldn't this crash if we try to call `EventRecorder.RecordEvent` on a `IEventRecording` not being instance of `EventRecorder`?

File: Src/FluentAssertions/Events/EventHandlerFactory.cs [hunk 15]
```diff
@@ -109,7 +109,7 @@ private static Type[] AppendParameterListThisReference(Type[] parameters)
         {
             var newList = new Type[parameters.Length + 1];
 
-            newList[0] = typeof(IEventRecorder);
+            newList[0] = typeof(IEventRecording);
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventHandlerFactory.cs:112]: I'm also curious if this should just be `EventRecorder`?

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 16]
```diff
@@ -13,84 +14,136 @@ namespace FluentAssertions
...
             }
 
-            return eventRecorder;
+            return new FilteredEventRecording(eventRecording, eventsMatchingPredicate);
         }
 
         /// <summary>
-        /// Asserts that at least one occurrence of the event had arguments matching all predicates.
+        /// Asserts that at least one occurrence of the events had arguments matching all predicates. Returns
+        /// only the events that matched that predicate.
```
Comment (jnyrup) [inline Src/FluentAssertions/EventRaisingExtensions.cs:99]: trailing whitespace (SA1028)

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 17]
```diff
@@ -13,84 +14,136 @@ namespace FluentAssertions
...
+                }
+
+                if (typedParameters.Any(parameter => compiledPredicate(parameter)))
+                {
+                    eventsMatchingPredicate.Add(@event);
+                }
             }
 
-            if (eventRecorder.All(recordedEvent => !recordedEvent.Parameters.OfType<T>().Any(parameter => compiledPredicate(parameter))))
+
```
Comment (jnyrup) [inline Src/FluentAssertions/EventRaisingExtensions.cs:82]: multiple empty lines (SA1507)

File: Src/FluentAssertions/Events/EventRecorder.cs [hunk 18]
```diff
@@ -69,35 +85,15 @@ public void Dispose()
...
-        /// Enumerate raised events
-        /// </summary>
-        public IEnumerator<RecordedEvent> GetEnumerator()
-        {
-            lock (lockable)
-            {
-                return raisedEvents.ToList().GetEnumerator();
+                EventObject = null;
             }
         }
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventRecorder.cs:91]: multiple empty lines (SA1507)

File: Src/FluentAssertions/Execution/AssertionScope.cs [hunk 19]
```diff
@@ -224,11 +224,30 @@ private Continuation FailWith(Func<string> failReasonFunc)
...
+        {
+            return FailWith(() => new FailReason(message, new object[0]));
+        }
+        /// <summary>
```
Comment (jnyrup) [inline Src/FluentAssertions/Execution/AssertionScope.cs:234]: missing newline after closing brace (SA1513)

File: Src/FluentAssertions/Events/EventRecorder.cs (hunk 6 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/EventRecorder.cs:123]: Correct.

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs [hunk 20]
```diff
@@ -1,17 +1,20 @@
-﻿using System;
-using System.ComponentModel;
-using System.Linq;
-#if NET47
+﻿#if NET47
 using System.Reflection;
 using System.Reflection.Emit;
 #endif
+
+#if !NETCOREAPP2_0
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:6]: I wonder what happens if we rename a file like that.

File: Src/FluentAssertions/Events/IMonitor.cs [hunk 21]
```diff
@@ -22,10 +24,7 @@ public interface IMonitor<T> : IDisposable
         /// </summary>
         EventAssertions<T> Should();
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/IMonitor.cs:25]: Well, why would you create an extension method on your own code?

File: Src/FluentAssertions/Events/EventHandlerFactory.cs (hunk 13 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/EventHandlerFactory.cs:30]: Yes.

File: Src/FluentAssertions/Events/EventHandlerFactory.cs (hunk 14 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Events/EventHandlerFactory.cs:16]: It will throw a NRE.

File: Src/FluentAssertions/Events/IMonitor.cs (hunk 21 above)
[the remark this answers is not in the document]
Comment (jnyrup) [reply Src/FluentAssertions/Events/IMonitor.cs:25]: We have `Should(this ExecutionTime executionTime)` `Should(this TypeSelector typeSelector)`.
I just found it odd to have `Should` in an interface.

File: Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs (hunk 20 above)
[the remark this answers is not in the document]
Comment (jnyrup) [reply Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs:6]: Then it just fails to build as `Monitor<T>(this T eventSource)` does not exist in the netstandard2.0 fluentAssertions.dll

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 22]
```diff
@@ -13,84 +14,136 @@ namespace FluentAssertions
...
             {
-                T[] parameters = recordedEvent.Parameters.OfType<T>().ToArray();
-                int parametersToCheck = Math.Min(parameters.Length, predicates.Length);
+                var typedParameters = @event.Parameters.OfType<T>().ToArray();
+                if (typedParameters.Any())
+                {
+                    hasArgumentOfRightType = true;
+                }
+
+                int parametersToCheck = Math.Min(typedParameters.Length, predicates.Length);
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/EventRaisingExtensions.cs:119]: You're right. It was wrong all along, but I'll fix it in this PR.

File: Src/FluentAssertions/Events/EventMonitor.cs [hunk 23]
```diff
@@ -45,23 +45,18 @@ public OccurredEvent[] OccurredEvents
                 IEnumerable<OccurredEvent> query =
                     from mapItem in recorderMap.ToArray()
```
Comment (jnyrup) [inline Src/FluentAssertions/Events/EventMonitor.cs:46]: Since this no longer uses the `Value` we can use `recorderMap.Keys` instead.

`public EventMetadata[] MonitoredEvents` can also use `.Values` instead of `.ToArray()` as it does not use `Key`.

File: docs/_pages/eventmonitoring.md [hunk 24]
```diff
@@ -52,47 +53,40 @@ Or...
...
 
-This generic version of `Monitor()` is also very useful if you wish to monitor events of a dynamically generated class using `System.Reflection.Emit`.
-Since events are dynamically generated and are not present in parent class non-generic version of `Monitor()` will not find the events.
-This way you can tell the event monitor which interface was implemented in the generated class.
+This generic version of `Monitor()` is also very useful if you wish to monitor events of a dynamically generated class using `System.Reflection.Emit`. Since events are dynamically generated and are not present in parent class non-generic version of `Monitor()` will not find the events. This way you can tell the event monitor which interface was implemented in the generated class.
 
 ```csharp
 POCOClass subject = EmitViewModelFromPOCOClass();
 
 using (var monitor = subject.Monitor<ISomeInterface>())
```
Comment (jnyrup) [inline docs/_pages/eventmonitoring.md:68]:
```suggestion
using var monitor = subject.Monitor<ISomeInterface>();
```

File: docs/_pages/eventmonitoring.md [hunk 25]
```diff
@@ -52,47 +53,40 @@ Or...
...
-You do that by providing a type which defines the events.
+`Monitor()` is a generic method, but you will usually have the compiler infer the type. You _can_ specify an explicit type to limit which events you want to listen to:
 
 ```csharp
 var subject = new ClassWithManyEvents();
-using (var monitor = subject.Monitor<IInterfaceWithFewEvents>();
-{
-    
-}
+using var monitor = subject.Monitor<IInterfaceWithFewEvents>()
```
Comment (jnyrup) [inline docs/_pages/eventmonitoring.md:60]:
```suggestion
using var monitor = subject.Monitor<IInterfaceWithFewEvents>();
```

File: docs/_pages/eventmonitoring.md [hunk 26]
```diff
@@ -12,11 +12,11 @@ Before you can invoke the assertion extensions, you must first tell Fluent Asser
 
 ```csharp
 var subject = new EditCustomerViewModel();
-using (var monitoredSubject = subject.Monitor())
-{
-    subject.Foo();
-    monitoredSubject.Should().Raise("NameChangedEvent");
-}
+using var monitoredSubject = subject.Monitor()
```
Comment (jnyrup) [inline docs/_pages/eventmonitoring.md:15]:
```suggestion
using var monitoredSubject = subject.Monitor();
```

File: docs/_pages/eventmonitoring.md [hunk 27]
```diff
@@ -52,47 +53,40 @@ Or...
...
+The `IMonitor` interface returned by `Monitor()` exposes a method named `GetRecordingFor` as well as the properties `MonitoredEvents` and `OccurredEvents` that you can use to directly interact with the monitor, e.g. to create your own extensions. For example:
 
 ```csharp
     var eventSource = new ClassThatRaisesEventsItself();
-    using (var monitor = eventSource.Monitor<IEventRaisingInterface>())
-    {
-        EventMetadata[] metadata = monitor.MonitoredEvents;
 
-        metadata.Should().BeEquivalentTo(new[]
+    using IMonitor monitor = eventSource.Monitor<IEventRaisingInterface>()
```
Comment (jnyrup) [inline docs/_pages/eventmonitoring.md:80]:
```suggestion
    using IMonitor monitor = eventSource.Monitor<IEventRaisingInterface>();
```

File: Src/FluentAssertions/EventRaisingExtensions.cs [hunk 28]
```diff
@@ -13,84 +14,138 @@ namespace FluentAssertions
...
             {
-                T[] parameters = recordedEvent.Parameters.OfType<T>().ToArray();
-                int parametersToCheck = Math.Min(parameters.Length, predicates.Length);
+                var typedParameters = @event.Parameters.OfType<T>().ToArray();
+                if (typedParameters.Any())
+                {
+                    hasArgumentOfRightType = true;
+                }
+
+                if (predicates.Length > typedParameters.Length)
```
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/EventRaisingExtensions.cs:118]: If there are less predicates, then apparently that person doesn't care. This is also what the tests seems to suggest.

File: docs/_pages/eventmonitoring.md (hunk 24 above)
Comment (dennisdoomen) [reply docs/_pages/eventmonitoring.md:68]: Didn't want to use that in the docs since not everybody may be on C# 8 yet.

File: Src/FluentAssertions/EventRaisingExtensions.cs (hunk 28 above)
[the remark this answers is not in the document]
Comment (jnyrup) [reply Src/FluentAssertions/EventRaisingExtensions.cs:118]: My immediate thought is that providing too few predicates should be symmetric to providing too many.
If only the first `predicates.Length` number of typedArguments need to match, then the error message should be `Expected the event to have at least {predicates.Length} parameters`.

File: docs/_pages/eventmonitoring.md (hunk 24 above)
Comment (jnyrup) [reply docs/_pages/eventmonitoring.md:68]: Then I suggest we keep a full `using` scope everywhere in the docs?

```c#
using (var monitor = ...)
{
}
```

File: Src/FluentAssertions/EventRaisingExtensions.cs (hunk 28 above)
[the remark this answers is not in the document]
Comment (dennisdoomen) [reply Src/FluentAssertions/EventRaisingExtensions.cs:118]: I don't agree with the first one. But I'll update the message.

File: docs/_pages/eventmonitoring.md (hunk 24 above)
Comment (dennisdoomen) [reply docs/_pages/eventmonitoring.md:68]: On second hand, it might be fine to remind people of new syntax options like that.
