### PR TITLE
Better support for NaN in numeric assertions on floats and doubles

### LINKED ISSUE #1690: NumericAssertions does not handle NaN correctly
### Description

`NumericAssertions` uses `CompareTo` to decide if a subject is e.g. smaller than the expected.
That is technically mixing different concepts, as `CompareTo` only decides the relative ordering between two items, i.e. how they should be sorted.
What `NumericAssertions` should be doing when "comparing" is arithmetic comparisons that corresponds to using operators like `<`, `==` and so on.

### Complete minimal example reproducing the issue

```csharp
double.NaN.Should().BeLessThan(0);
```

### Expected behavior:
Should fail, as comparing `NaN` to anything using `<`, `<=`, `==`, `>=` or `>` returns false.

### Actual behavior:
The test passes.

### Versions

* Which version of Fluent Assertions are you using?
  * 6.1.0 (master)

### PR DESCRIPTION
**Pull request by dennisdoomen**
Assertions where floats and doubles were compared to NaN did not always work as expected, especially when "larger than",  "smaller than", ranges and approximation were involved. Also, using NaN as an argument is also no longer supported (and not desired).

Fixes #1690

**Note** Review without whitespace

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [x] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [x] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

File: Src/FluentAssertions/Numeric/NumericAssertions.cs [hunk 1]
```diff
@@ -208,7 +213,7 @@ public AndConstraint<TAssertions> BeLessThan(T expected, string because = "", pa
             params object[] becauseArgs)
         {
```
Comment (jnyrup) [inline Src/FluentAssertions/Numeric/NumericAssertions.cs:214]: Add `IsNaN(expected)` check

File: Src/FluentAssertions/Numeric/NumericAssertions.cs [hunk 2]
```diff
@@ -449,5 +474,7 @@ public AndConstraint<TAssertions> NotBeOfType(Type unexpectedType, string becaus
         /// <inheritdoc/>
         public override bool Equals(object obj) =>
             throw new NotSupportedException("Calling Equals on Assertion classes is not supported.");
+
+        internal virtual bool IsNaN(T value) => false;
```
Comment (jnyrup) [inline Src/FluentAssertions/Numeric/NumericAssertions.cs:478]: If you bother this could be `private protected` for minimum visibility.

File: Src/FluentAssertions/NumericAssertionsExtensions.cs [hunk 3]
```diff
@@ -1181,6 +1196,11 @@ public static class NumericAssertionsExtensions
             double unexpectedValue, double precision, string because = "",
             params object[] becauseArgs)
         {
+            if (double.IsNaN(unexpectedValue))
```
Comment (jnyrup) [inline Src/FluentAssertions/NumericAssertionsExtensions.cs:1199]: This is the only of the eight extension methods on `NullableNumericAssertions` where the `IsNaN` check is added.

Comment (dennisdoomen) [reply Src/FluentAssertions/NumericAssertionsExtensions.cs:1199]: Unless, I'm missing the point, all of them end up calling the same methods, which are protected by `IsNan`.

Comment (jnyrup) [reply Src/FluentAssertions/NumericAssertionsExtensions.cs:1199]: Roger.
Then this one is not necessary, as `unexpectedValue` is checked inside the call to `NotBeApproximately` on line 1212.

What triggered me was that I saw 5, i.e. an odd number of added calls to `IsNaN`, either float or double had too many/few calls to `IsNaN`.

File: Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs [hunk 4]
```diff
@@ -666,6 +817,54 @@ public void When_a_nullable_numeric_null_value_is_not_greater_than_or_equal_to_i
                     .Should().Throw<XunitException>()
                     .WithMessage("*null*");
             }
+
+            [Fact]
+            public void NaN_is_never_greater_or_equal_to_another_float()
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs:822]: greather_ _than_ _or_equal_to

File: Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs [hunk 5]
```diff
@@ -817,6 +1064,54 @@ public void When_a_nullable_numeric_null_value_is_not_less_than_or_equal_to_it_s
                     .Should().Throw<XunitException>()
                     .WithMessage("*null*");
             }
+
+            [Fact]
+            public void NaN_is_never_less_than_equal_to_another_float()
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs:1069]: less_than_ _or_ _equal_to

File: Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs [hunk 6]
```diff
@@ -864,6 +1159,72 @@ public void When_a_nullable_numeric_null_value_is_not_in_range_it_should_throw()
                     .Should().Throw<XunitException>()
                     .WithMessage("*null*");
             }
+
+            [Fact]
+            public void A_NaN_is_never_in_range_of_two_floats()
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs:1164]:
```suggestion
            public void NaN_is_never_in_range_of_two_floats()
```

File: Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs [hunk 7]
```diff
@@ -864,6 +1159,72 @@ public void When_a_nullable_numeric_null_value_is_not_in_range_it_should_throw()
...
+
+                // Assert
+                act
+                    .Should().Throw<XunitException>()
+                    .WithMessage(
+                        "Expected value to be between*4* and*5*, but found*NaN*");
+            }
+
+            [Fact]
+            public void A_float_can_never_be_in_a_range_containing_NaN()
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs:1180]: Use `InlineData` like for double

File: Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs [hunk 8]
```diff
@@ -38,7 +38,7 @@ public void When_a_negative_value_is_positive_it_should_throw()
             public void When_a_zero_value_is_positive_it_should_throw()
             {
                 // Arrange
-                int value = 0;
+                double value = double.NaN;
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs:41]: Was this change intentional?
The method name says "zero value", but body uses NaN

**Review by jnyrup — APPROVED** [review]

File: Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs (hunk 8 above)
Comment (dennisdoomen) [reply Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs:41]: Good catch. Must have been experimenting with something.
