### PR TITLE
Guard methods against assertion scope `[Not]HaveExplicit(Property|Method)`

### LINKED ISSUE #2400: Methods are not guarded against being wrapped in an `AssertionScope`
### Description

When doing #2399 I found that these four methods in `TypeAssertions` are not guarded against being wrapped in an `AssertionScope`.

* `HaveExplicitProperty`
* `NotHaveExplicitProperty`
* `HaveExplicitMethod`
* `NotHaveExplicitMethod`

See how we call `Should().Implement()` and the make the next assertion without any guards.
https://github.com/fluentassertions/fluentassertions/blob/f4c3d56d5524996f6dc6bd02024fce88f55941d9/Src/FluentAssertions/Types/TypeAssertions.cs#L976-L984

### Reproduction Steps

```cs
var act = () =>
{
    using var _ = new AssertionScope();
    typeof(int).Should().HaveExplicitProperty(typeof(IExplicitInterface), "Foo");
};

act.Should().Throw<XunitException>()
    .WithMessage("Expected type System.Int32 to*implement IExplicitInterface.Foo, but it does not.");
```

### Expected behavior

pass

### Actual behavior

```
Expected exception message to match the equivalent of "Expected type System.Int32 to*implement IExplicitInterface.Foo, but it does not.", but "Expected type System.Int32 to implement interface FluentAssertions.Specs.Types.IExplicitInterface, but it does not.
Expected System.Int32 to explicitly implement FluentAssertions.Specs.Types.IExplicitInterface.Foo, but it does not.
" does not.
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

### PR DESCRIPTION
**Pull request by IT-VBFK**
Fixes #2400 

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [x] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [x] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

File: Src/FluentAssertions/Types/TypeAssertions.cs [hunk 1]
```diff
@@ -462,18 +462,7 @@ public AndConstraint<TypeAssertions> Implement(Type interfaceType, string becaus
...
-            .BecauseOf(because, becauseArgs)
-            .WithExpectation("Expected type {0} to implement interface {1}{reason}", Subject, interfaceType)
-            .ForCondition(interfaceType.IsInterface)
-            .FailWith(", but {0} is not an interface.", interfaceType)
-            .Then
-            .ForCondition(containsInterface)
-            .FailWith(", but it does not.")
-            .Then
-            .ClearExpectation();
+        ImplementInternal(interfaceType, because, becauseArgs);
```
Comment (IT-VBFK) [inline Src/FluentAssertions/Types/TypeAssertions.cs:465]: This is just a suggestion.. could most definitely be a better name...

`SubjectImplenents(...)` ?
`DoesImplement(...)` ?

**Review by jnyrup — APPROVED** [review]

File: Src/FluentAssertions/Types/TypeAssertions.cs (hunk 1 above)
Comment (IT-VBFK) [reply Src/FluentAssertions/Types/TypeAssertions.cs]: I have called it `SubjectImplenents()`

File: Src/FluentAssertions/Types/TypeAssertions.cs [hunk 2]
```diff
@@ -495,6 +484,22 @@ public AndConstraint<TypeAssertions> Implement<TInterface>(string because = "",
         return Implement(typeof(TInterface), because, becauseArgs);
     }
 
+    private bool SubjectImplements(Type interfaceType, string because = "", params object[] becauseArgs)
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Types/TypeAssertions.cs:487]: 🔧 We prefer to have a method always follow its invocations (like a book). So it should be moved below the last member that uses it.
🤔 Since this method actually throws under normal circumstances, I think naming it some like `AssertSubjectImplements`

File: Src/FluentAssertions/Types/TypeAssertions.cs [hunk 3]
```diff
@@ -495,6 +484,22 @@ public AndConstraint<TypeAssertions> Implement<TInterface>(string because = "",
...
+    {
+        bool containsInterface = interfaceType.IsAssignableFrom(Subject) && interfaceType != Subject;
```
Comment (dennisdoomen) [inline Src/FluentAssertions/Types/TypeAssertions.cs:489]: 🤔 Why not use that condition inline, inside the `ForCondition`?

**Review by dennisdoomen — CHANGES_REQUESTED** [review]

**Review by dennisdoomen — APPROVED** [review]

**Comment by IT-VBFK** [comment]
Label `bug`? 😉
