### PR TITLE
Properly report the path even if custom mapping is used

### LINKED ISSUE #2812: BeEquivalentTo comparision When deep object and WithMapping
### Description

I have two objects that are similar and I apply a `BeEquivalentTo` for members comparison. But the problem is that one property that is inside a `WithMapping` property is not present in the destination object.

I have finally to call `Excluding((IMemberInfo ctx))` for that property

### Reproduction Steps

```csharp
using FluentAssertions;
using FluentAssertions.Equivalency;
using Xunit;

namespace NameSpace;

public class MappingTest
{
    public class Customer
    {
        public Residence Address { get; set; }
    }

    public class Residence
    {
        public string Address { get; set; }
    }

    public class CustomerDto
    {
        public ResidenceDto AddressInformation { get; set; }
    }

    public class ResidenceDto
    {
        public string Address { get; set; }

        public bool IsValidated { get; set; }
    }

    [Fact]
    public void CustomerDto_To_Customer_ShouldBeEquivalent()
    {
        // Arrange
        var req = new CustomerDto
        {
            AddressInformation = new ResidenceDto
            {
                Address = "foo",
                IsValidated = true
            }
        };
        
        // Act
        var res = new Customer
        {
            Address = new Residence()
            {
                Address = "foo"
            }
        };
        
        // Assert
        res.Should().BeEquivalentTo(req, o => o
        .WithMapping<CustomerDto, Customer>(s => s.AddressInformation, d => d.Address)
        //.Excluding((IMemberInfo ctx) => ctx.DeclaringType.IsAssignableFrom(typeof(ResidenceDto)) && ctx.Name == nameof(ResidenceDto.IsValidated))
        .Excluding(r => r.AddressInformation.IsValidated));
    }
}
```

### Expected behavior

The simple `Excluding(r => r.AddressInformation.IsValidated)` should work

### Actual behavior

Expectation has property `res.Address.IsValidated` that the other object does not have

### Regression?

_No response_

### Known Workarounds

The use of `Excluding((IMemberInfo ctx))`

### Configuration

_No response_

### Other information

_No response_

### Are you willing to help with a pull-request?

No

### PR DESCRIPTION
**Pull request by dennisdoomen**
This pull request includes several important changes to improve the consistency and accuracy of member path handling in the `FluentAssertions` library. The changes focus on replacing the use of `Name` and `PathAndName` with `Subject` and `Expectation` properties in various classes and methods.

### Member Path Handling Improvements:

* [`Src/FluentAssertions/Common/MemberPath.cs`](diffhunk://#diff-577dd9dac264ec2984041459dcf9793a3c07c98a3bf790a200241b5d2d3cc4fbL23-R23): Changed the constructor to use `member.Expectation.Name` instead of `member.Name`.
* [`Src/FluentAssertions/Common/TypeExtensions.cs`](diffhunk://#diff-4cd9833333753360b720fc8774b3a69379049ef8480483a504183c4c8a3a53e4L141-R141): Updated the `IsEquivalentTo` method to compare `property.Expectation.Name` with `otherProperty.Expectation.Name` instead of `property.Name`.

### Consistency in Node Handling:

* [`Src/FluentAssertions/Equivalency/Node.cs`](diffhunk://#diff-e9afe45a1e0f0a238d703b116e1a2f01f6f1c07b21247a16ce4ddda9b29d2ccfL15-R16): Replaced `Path` and `PathAndName` with `Subject` and `Expectation` properties. Added the `AdjustForRemappedSubject` method to handle remapped subject members during structural equivalency checks. [[1]](diffhunk://#diff-e9afe45a1e0f0a238d703b116e1a2f01f6f1c07b21247a16ce4ddda9b29d2ccfL15-R16) [[2]](diffhunk://#diff-e9afe45a1e0f0a238d703b116e1a2f01f6f1c07b21247a16ce4ddda9b29d2ccfL30-R71) [[3]](diffhunk://#diff-e9afe45a1e0f0a238d703b116e1a2f01f6f1c07b21247a16ce4ddda9b29d2ccfL87-R85) [[4]](diffhunk://#diff-e9afe45a1e0f0a238d703b116e1a2f01f6f1c07b21247a16ce4ddda9b29d2ccfR94-R116)
* [`Src/FluentAssertions/Equivalency/INode.cs`](diffhunk://#diff-9bf751f9b4e02187e7db5c7af36c42589a51293acc43a21dc6b4ad8b3d3f9fc5L18-L25): Removed `Name`, `Path`, `PathAndName`, and `Description` properties. Added `Subject` and `Expectation` properties. [[1]](diffhunk://#diff-9bf751f9b4e02187e7db5c7af36c42589a51293acc43a21dc6b4ad8b3d3f9fc5L18-L25) [[2]](diffhunk://#diff-9bf751f9b4e02187e7db5c7af36c42589a51293acc43a21dc6b4ad8b3d3f9fc5L37-R38) [[3]](diffhunk://#diff-9bf751f9b4e02187e7db5c7af36c42589a51293acc43a21dc6b4ad8b3d3f9fc5L65-L72) [[4]](diffhunk://#diff-9bf751f9b4e02187e7db5c7af36c42589a51293acc43a21dc6b4ad8b3d3f9fc5R58-R67)

### Adjustments in Equivalency Validation:

* [`Src/FluentAssertions/Equivalency/EquivalencyValidationContext.cs`](diffhunk://#diff-fee28d60cb5893e8661b289db68d9852d76d99cf27d70f60f326124c8d36fcdcL77-R85): Updated `IsCyclicReference` and `ToString` methods to use `CurrentNode.Subject.PathAndName` instead of `CurrentNode.PathAndName`.
* [`Src/FluentAssertions/Equivalency/AssertionChainExtensions.cs`](diffhunk://#diff-f6d0e1e366b7e364c16e79c1f7152e2fbf920d12cd205ad071f7ff4673beb357L13-R13): Modified the `For` method to use `context.CurrentNode.Subject.Description` instead of `context.CurrentNode.Description`.

### Updates in Matching Rules:

* [`Src/FluentAssertions/Equivalency/Matching/MappedMemberMatchingRule.cs`](diffhunk://#diff-90a916bfec24a37c63a96b92a896f8b3287ae1e05ac11a447bbdf29e79493cf2L36-R36): Changed the `Match` method to compare `expectedMember.Subject.Name` with `expectationMemberName` instead of `expectedMember.Name`.
* [`Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs`](diffhunk://#diff-f495469cc21ec31890dcd0c94b00050d5b6053817efcdbcc4a1c97222bcb9af5L19-R19): Updated the `Match` method to use `expectedMember.Subject.Name` instead of `expectedMember.Name`. [[1]](diffhunk://#diff-f495469cc21ec31890dcd0c94b00050d5b6053817efcdbcc4a1c97222bcb9af5L19-R19) [[2]](diffhunk://#diff-f495469cc21ec31890dcd0c94b00050d5b6053817efcdbcc4a1c97222bcb9af5L28-R28) [[3]](diffhunk://#diff-f495469cc21ec31890dcd0c94b00050d5b6053817efcdbcc4a1c97222bcb9af5L37-R42)

These changes collectively enhance the handling of member paths and improve the overall consistency and accuracy of the `FluentAssertions` library.

Closes #2812

## IMPORTANT 

* [x] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [x] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [x] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by jnyrup** [comment]
Thinking aloud: since #2812 has a workaround and this is not a regression, should this be targeted against `develop` instead of `main`?

**Comment by dennisdoomen** [comment]
> Thinking aloud: since #2812 has a workaround and this is not a regression, should this be targeted against `develop` instead of `main`?

My thought was that if this can be fixed in a non-breaking way, I might consider targeting `main`. But realistically, it's probably going to be targeting `develop` instead.

File: Src/FluentAssertions/Equivalency/Pathway.cs [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+        this.getDescription = getDescription;
+    }
+
+    /// <summary>
+    /// Gets the path of the field or property without the name.
+    /// </summary>
+    public string Path
+    {
+        get => path;
+        init
```
Comment (jnyrup) [inline Src/FluentAssertions/Equivalency/Pathway.cs:42]:
```suggestion
        private init
```

File: Src/FluentAssertions/Equivalency/Node.cs [hunk 2]
```diff
@@ -94,25 +91,29 @@ public static INode From<T>(GetSubjectId getSubjectId)
...
+        Pathway.GetDescription getDescription = pathAndName => $"{parent.GetSubjectId().Combine(pathAndName)}";
+
         return new Node
         {
             Type = typeof(T),
             ParentType = parent.Type,
-            Name = "[" + index + "]",
-            Path = parent.PathAndName,
+            Subject = new Pathway(parent.Subject, "[" + index + "]", getDescription),
+            Expectation = new Pathway(parent.Expectation, "[" + index + "]", getDescription),
```
Comment (jnyrup) [inline Src/FluentAssertions/Equivalency/Node.cs:101]: Suggestion: cache `"[" + index + "]"` in a variable.

Same suggestion for `"[" + key + "]"` in `FromDictionaryItem`

File: Src/FluentAssertions/Equivalency/Node.cs [hunk 3]
```diff
@@ -94,25 +91,29 @@ public static INode From<T>(GetSubjectId getSubjectId)
...
             GetSubjectId = parent.GetSubjectId,
             RootIsCollection = parent.RootIsCollection
         };
     }
 
     public static INode FromDictionaryItem<T>(object key, INode parent)
     {
+        Pathway.GetDescription getDescription = pathAndName => $"{parent.GetSubjectId().Combine(pathAndName)}";
```
Comment (jnyrup) [inline Src/FluentAssertions/Equivalency/Node.cs:109]:
```suggestion
        Pathway.GetDescription getDescription = pathAndName => parent.GetSubjectId().Combine(pathAndName);
```

File: Src/FluentAssertions/Equivalency/Node.cs [hunk 4]
```diff
@@ -94,25 +91,29 @@ public static INode From<T>(GetSubjectId getSubjectId)
 
     public static INode FromCollectionItem<T>(string index, INode parent)
     {
+        Pathway.GetDescription getDescription = pathAndName => $"{parent.GetSubjectId().Combine(pathAndName)}";
```
Comment (jnyrup) [inline Src/FluentAssertions/Equivalency/Node.cs:94]:
```suggestion
        Pathway.GetDescription getDescription = pathAndName => parent.GetSubjectId().Combine(pathAndName);
```

File: Src/FluentAssertions/Common/StringExtensions.cs [hunk 5]
```diff
@@ -78,11 +72,6 @@ public static string Combine(this string @this, string other, string separator =
             return other.Length != 0 ? other : string.Empty;
         }
 
-        if (other.Length == 0)
-        {
-            return @this;
-        }
```
Comment (jnyrup) [inline Src/FluentAssertions/Common/StringExtensions.cs:84]: I introduced that in https://github.com/fluentassertions/fluentassertions/pull/817 but it might no longer be relevant?

**Review by jnyrup — COMMENTED** [review]
Nice work!

I guess https://x.com/ddoomen/status/1867852759787360343 was about this PR.
Could you include the before and after benchmarks here?

**Comment by dennisdoomen** [comment]
> Could you include the before and after benchmarks here?

I didn't keep them, but my focus was on making sure the number of calls to `DetermineCallerIdentifier` wasn't more than I expected because of the new tests.

File: Src/FluentAssertions/Common/StringExtensions.cs (hunk 5 above)
Comment (dennisdoomen) [reply Src/FluentAssertions/Common/StringExtensions.cs:84]: It wasn't covered by any code, so I decided to remove it.

**Review by jnyrup — APPROVED** [review]
