### PR TITLE
Fix timeout check in WithResult extension

### LINKED ISSUE #1969: WithResult extension is always waiting for the Task to be completed
With #1478 I implemented the extension methods `WithResult` for assertions on asynchronous operations.
While playing around with this methods together with failed `Should().CompleteWithinAsync` I found that it could be unexpected, that these methods explicitly waiting for the completion of the `Task`.
The original intention of the assertions `CompleteWithinAsync` were ensuring tests will not hang forever. With awaiting the `Task` the "timeout" is skipped and the test may hang.

Today I think whether it would be better to not `await` the `Task` and instead check whether it is already completed.
In case the `Task` is not completed, further the result is not relevant anymore, isn't it?

### PR DESCRIPTION
**Pull request by lg2de**
## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).

Fixes #1969

### CODE REVIEW

File: Src/FluentAssertions/AsyncAssertionsExtensions.cs [hunk 1]
```diff
@@ -22,6 +23,11 @@ public static class AsyncAssertionsExtensions
         this Task<AndWhichConstraint<GenericAsyncFunctionAssertions<T>, T>> task,
         T expected, string because = "", params object[] becauseArgs)
     {
+        if (AssertionScope.Current.HasFailures())
+        {
+            return null;
+        }
```
Comment (jnyrup) [inline Src/FluentAssertions/AsyncAssertionsExtensions.cs:29]: Other things than `CompleteWithinAsync` could have added a failure to the `AssertionScope`.

```cs
using var _ = new AssertionScope();
true.Should().BeFalse();
await func.Should().CompleteWithinAsync(100.Milliseconds()).WithResult(2);
```

Comment (lg2de) [reply Src/FluentAssertions/AsyncAssertionsExtensions.cs:29]: Yes, I know.
But what is the consequence? We skip one check while another already caused a failed test.

This is just a prove of concept. I'm thinking about a solution to prevent from test not completing.

Comment (jnyrup) [reply Src/FluentAssertions/AsyncAssertionsExtensions.cs:29]: The whole idea of `AssertionScope` is to continue asserting where possible.
So if `true.Should().BeFalse();` fails, but `CompleteWithinAsync` succeeds, `WithResult` should be executed.

But I get the case you want to solve, just wanted to drop a note.

File: Src/FluentAssertions/AsyncAssertionsExtensions.cs [hunk 2]
```diff
@@ -18,6 +18,12 @@ public static class AsyncAssertionsExtensions
     /// <param name="becauseArgs">
     /// Zero or more objects to format using the placeholders in <paramref name="because"/>.
     /// </param>
+    /// <remarks>
+    /// Please note that this assertion cannot identify whether the previous assertion was successful or not.
+    /// In case it was not successful and it is running within an active <see cref="FluentAssertions.Execution.AssertionScope"/>
+    /// there is not current result to compare.
```
Comment (dennisdoomen) [inline Src/FluentAssertions/AsyncAssertionsExtensions.cs:24]:
```suggestion
    /// there is no current result to compare.
```

File: Tests/FluentAssertions.Specs/FakeClock.cs [hunk 3]
```diff
@@ -9,7 +9,7 @@ namespace FluentAssertions.Specs;
 /// Implementation of <see cref="IClock"/> for testing purposes only.
 /// </summary>
 /// <remarks>
-/// It allows you to control the "current" time.
+/// It allows you to control the "current" time for internal delays.
```
Comment (dennisdoomen) [inline Tests/FluentAssertions.Specs/FakeClock.cs:12]:
```suggestion
/// It allows you to control the "current" date and time for test purposes.
```

File: Src/FluentAssertions/AsyncAssertionsExtensions.cs (hunk 2 above)
Comment (dennisdoomen) [inline Src/FluentAssertions/AsyncAssertionsExtensions.cs:24]:
```suggestion
    ///  there is no current result to compare with.
```

File: Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs [hunk 4]
```diff
@@ -165,6 +164,28 @@ public async Task When_task_completes_late_it_in_assertion_scope_should_fail()
             await action.Should().ThrowAsync<XunitException>();
         }
 
+        [Fact]
+        public async Task When_task_does_not_completes_the_result_extension_does_not_hang()
```
Comment (dennisdoomen) [inline Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs:168]:
```suggestion
        public async Task When_task_does_not_complete_the_result_extension_does_not_hang()
```

File: docs/_pages/releases.md [hunk 5]
```diff
@@ -12,6 +12,7 @@ sidebar:
 ### What's new
 
 ### Fixes
+* Fixes hanging of `CompleteWithinAsync` when using with `WithResult` and `AssertionScope`. - [#2101](https://github.com/fluentassertions/fluentassertions/pull/2101)
```
Comment (jnyrup) [inline docs/_pages/releases.md:15]:
```suggestion
* Fixed hanging of `CompleteWithinAsync` when used with `WithResult` and `AssertionScope` - [#2101](https://github.com/fluentassertions/fluentassertions/pull/2101)
```

File: Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs [hunk 6]
```diff
@@ -165,6 +164,28 @@ public async Task When_task_completes_late_it_in_assertion_scope_should_fail()
...
+                Func<Task<int>> func = () => taskFactory.Task;
+                using var _ = new AssertionScope();
+                return func.Should(timer).CompleteWithinAsync(100.Milliseconds()).WithResult(2);
+            };
+            timer.Complete();
+
+            // Assert
+            var assertionTask = action.Should().ThrowAsync<XunitException>()
+                .WithMessage("Expected*to complete within 100ms.*Expected return*to be 2, but found 0.");
+            await this.Awaiting(x => assertionTask).Should().CompleteWithinAsync(200.Seconds());
```
Comment (jnyrup) [inline Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs:186]: Adding `using static FluentAssertions.FluentActions;`

```suggestion
            await Awaiting(() => assertionTask).Should().CompleteWithinAsync(200.Seconds());
```

**Review by jnyrup — COMMENTED** [review]
I simply love when such edge-cases has a simple and fitting code change.

**Review by jnyrup — APPROVED** [review]

**Review by dennisdoomen — APPROVED** [review]

**Comment by dennisdoomen** [comment]
Needs a rebase...
